[book]
title = "Starweaver"
description = "Rust agent SDK documentation"
authors = ["Wh1isper"]
language = "en"
src = "docs"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/Wh1isper/starweaver"
edit-url-template = "https://github.com/Wh1isper/starweaver/edit/main/{path}"
site-url = "/"
cname = "starweaver.wh1isper.top"
additional-js = ["docs/mermaid-init.js"]

[output.html.fold]
enable = true
level = 1

[output.html.print]
enable = false
