use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use serde_json::{Value, json};
use sha2::{Digest as _, Sha256};

use crate::common::{root, sort_value};

use super::{bundle, generate_typescript, lint, model::ProtocolIr};

const EXCLUSIVE_GENERATED_ROOTS: &[&str] = &[
    "crates/starweaver-rpc-core/src/generated",
    "apps/starweaver-desktop/src/generated/host",
    "apps/starweaver-desktop/src-tauri/src/generated/host",
    "protocol/host/generated",
];
const AUTOGENERATED_PERMISSIONS_ROOT: &str =
    "apps/starweaver-desktop/src-tauri/permissions/autogenerated";
const CAPABILITIES_ROOT: &str = "apps/starweaver-desktop/src-tauri/capabilities";
const GENERATED_HOST_CAPABILITY: &str =
    "apps/starweaver-desktop/src-tauri/capabilities/generated-host.json";
const RPC_IDL_GENERATED_MARKER: &[u8] = b"@generated by `cargo run -p xtask -- generate-rpc-idl`";
const RPC_IDL_CAPABILITY_MARKER: &[u8] = b"Generated least-authority host operation fragment";

pub struct GeneratedOutputs {
    pub files: BTreeMap<PathBuf, Vec<u8>>,
}

impl GeneratedOutputs {
    pub fn build(repository: &Path) -> Result<Self, String> {
        let protocol_root = repository.join("protocol/host");
        let bundled = bundle::build(&protocol_root)?;
        let ir = ProtocolIr::from_bundle(&bundled.value)?;
        lint::check(&ir)?;
        if bundled.digest != ir.identity.schema_digest {
            return Err(
                "bundled digest does not match the normalized protocol identity".to_string(),
            );
        }

        let mut files = BTreeMap::new();
        files.insert(
            PathBuf::from("protocol/host/generated/starweaver-host.openrpc.json"),
            bundled.bytes.clone(),
        );
        files.extend(super::generate_rust::generate(&ir)?);

        files.extend(super::generate_desktop::generate(repository, &ir)?);
        format_desktop_outputs(repository, &mut files)?;

        let manifest_path = PathBuf::from("protocol/host/generated/manifest.json");
        let manifest = render_manifest(&ir, &bundled.sources, &files)?;
        files.insert(manifest_path, manifest);
        Ok(Self { files })
    }

    pub fn check(&self, repository: &Path) -> Result<(), String> {
        let expected = self.files.keys().cloned().collect::<BTreeSet<_>>();
        let actual = generator_owned_files(repository)?;
        let obsolete = actual.difference(&expected).collect::<Vec<_>>();
        if !obsolete.is_empty() {
            return Err(format!(
                "obsolete generated RPC IDL output(s): {}; run make rpc-idl-generate",
                display_paths(&obsolete)
            ));
        }
        let missing = expected.difference(&actual).collect::<Vec<_>>();
        if !missing.is_empty() {
            return Err(format!(
                "missing generated RPC IDL output(s): {}; run make rpc-idl-generate",
                display_paths(&missing)
            ));
        }
        for (relative, expected) in &self.files {
            let path = repository.join(relative);
            let actual = fs::read(&path).map_err(|error| {
                format!(
                    "read {}: {error}; run make rpc-idl-generate",
                    path.display()
                )
            })?;
            if actual != *expected {
                return Err(format!(
                    "{} is stale; run make rpc-idl-generate",
                    path.display()
                ));
            }
        }
        Ok(())
    }

    pub fn promote(&self, repository: &Path) -> Result<(), String> {
        self.promote_with_failure_injection(repository, None)
    }

    pub(super) fn promote_with_failure_injection(
        &self,
        repository: &Path,
        fail_before_promotion: Option<usize>,
    ) -> Result<(), String> {
        let staging = tempfile::tempdir().map_err(|error| error.to_string())?;
        for (relative, bytes) in &self.files {
            let staged = staging.path().join(relative);
            if let Some(parent) = staged.parent() {
                fs::create_dir_all(parent).map_err(|error| error.to_string())?;
            }
            fs::write(&staged, bytes)
                .map_err(|error| format!("write {}: {error}", staged.display()))?;
        }
        let expected = self.files.keys().cloned().collect::<BTreeSet<_>>();
        let mut operations = expected.clone();
        operations.extend(
            generator_owned_files(repository)?
                .difference(&expected)
                .cloned(),
        );

        let mut journal = Vec::new();
        for (index, relative) in operations.iter().enumerate() {
            let target = repository.join(relative);
            if let Some(parent) = target.parent()
                && let Err(error) = fs::create_dir_all(parent)
            {
                rollback(&journal);
                return Err(format!("create {}: {error}", parent.display()));
            }
            let backup = match backup_path(&target, index) {
                Ok(backup) => backup,
                Err(error) => {
                    rollback(&journal);
                    return Err(error);
                }
            };
            let exists = match path_exists(&target) {
                Ok(exists) => exists,
                Err(error) => {
                    rollback(&journal);
                    return Err(error);
                }
            };
            let backup = if exists {
                if let Err(error) = fs::rename(&target, &backup) {
                    rollback(&journal);
                    return Err(format!("backup {}: {error}", target.display()));
                }
                Some(backup)
            } else {
                None
            };
            journal.push((target.clone(), backup));
            if fail_before_promotion == Some(index) {
                rollback(&journal);
                return Err(format!(
                    "injected promotion failure before {}",
                    target.display()
                ));
            }
            if expected.contains(relative)
                && let Err(error) = fs::rename(staging.path().join(relative), &target)
            {
                rollback(&journal);
                return Err(format!("promote {}: {error}", target.display()));
            }
        }
        for backup in journal.into_iter().filter_map(|(_, backup)| backup) {
            remove_path(&backup).map_err(|error| {
                format!("remove promotion backup {}: {error}", backup.display())
            })?;
        }
        Ok(())
    }
}

pub fn generate(args: &[String]) -> Result<(), String> {
    no_args(args, "generate-rpc-idl")?;
    let repository = root()?;
    GeneratedOutputs::build(&repository)?.promote(&repository)
}

pub fn check_all(args: &[String]) -> Result<(), String> {
    no_args(args, "check-rpc-idl")?;
    let repository = root()?;
    GeneratedOutputs::build(&repository)?.check(&repository)?;
    check_complete_typescript_runtime(&repository)
}

fn check_complete_typescript_runtime(repository: &Path) -> Result<(), String> {
    let bundled = bundle::build(&repository.join("protocol/host"))?;
    let ir = ProtocolIr::from_bundle(&bundled.value)?;
    lint::check(&ir)?;
    let staging = tempfile::tempdir().map_err(|error| error.to_string())?;
    for (relative, bytes) in generate_typescript::generate(&ir)? {
        let path = staging.path().join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|error| error.to_string())?;
        }
        fs::write(&path, bytes).map_err(|error| {
            format!(
                "write generated TypeScript runtime {}: {error}",
                path.display()
            )
        })?;
    }

    let valid = request_corpus(repository, "protocol/host/examples")?;
    let invalid = request_corpus(repository, "protocol/host/fixtures/invalid/params")?;
    if valid.is_empty() || invalid.is_empty() {
        return Err(
            "TypeScript runtime gate requires non-empty valid and invalid corpora".to_string(),
        );
    }
    let runner = format!(
        r#"import {{ encodeHostRequest }} from "./generated/codecs.js";
import type {{ HostMethodName, RequestId }} from "./generated/types.js";
import {{ HostValidationError, decimalU64FromBigInt, decimalU64ToBigInt, parseTimestamp }} from "./generated/validators.js";

type Fixture = {{ readonly path: string; readonly request: {{ readonly id?: unknown; readonly method: string; readonly params: unknown }} }};
const valid = {} as unknown as readonly Fixture[];
const invalid = {} as unknown as readonly Fixture[];
const encode = encodeHostRequest as unknown as (id: RequestId, method: HostMethodName, params: unknown) => Uint8Array;
for (const fixture of valid) {{
  encode((fixture.request.id ?? "typescript-fixture") as RequestId, fixture.request.method as HostMethodName, fixture.request.params);
}}
for (const fixture of invalid) {{
  let rejected = false;
  try {{
    encode("typescript-invalid-fixture" as RequestId, fixture.request.method as HostMethodName, fixture.request.params);
  }} catch (error) {{
    if (!(error instanceof HostValidationError)) throw error;
    rejected = true;
  }}
  if (!rejected) throw new Error(`invalid fixture was accepted: ${{fixture.path}}`);
}}
parseTimestamp("2024-02-29T00:00:00Z");
for (const timestamp of ["2023-02-29T00:00:00Z", "2025-99-99TnonsenseZ", "2025-01-01T00:00:00+00:00"]) {{
  let rejected = false;
  try {{ parseTimestamp(timestamp); }} catch (error) {{ if (!(error instanceof HostValidationError)) throw error; rejected = true; }}
  if (!rejected) throw new Error(`invalid timestamp was accepted: ${{timestamp}}`);
}}
const maximumU64 = 18446744073709551615n;
if (decimalU64ToBigInt(decimalU64FromBigInt(maximumU64)) !== maximumU64) throw new Error("DecimalU64 maximum failed round trip");
for (const value of [-1n, maximumU64 + 1n]) {{
  let rejected = false;
  try {{ decimalU64FromBigInt(value); }} catch (error) {{ if (!(error instanceof HostValidationError)) throw error; rejected = true; }}
  if (!rejected) throw new Error(`out-of-range DecimalU64 was accepted: ${{value}}`);
}}
"#,
        serde_json::to_string(&valid).map_err(|error| error.to_string())?,
        serde_json::to_string(&invalid).map_err(|error| error.to_string())?,
    );
    fs::write(staging.path().join("validator-runtime-test.ts"), runner)
        .map_err(|error| format!("write TypeScript validator runner: {error}"))?;
    fs::write(
        staging.path().join("package.json"),
        "{\"type\":\"module\"}\n",
    )
    .map_err(|error| format!("write TypeScript runtime package metadata: {error}"))?;
    let type_roots = repository.join("apps/starweaver-desktop/node_modules/@types");
    let tsconfig = json!({
        "compilerOptions": {
            "lib": ["ES2022", "DOM", "DOM.Iterable"],
            "module": "NodeNext",
            "moduleResolution": "NodeNext",
            "noEmitOnError": true,
            "outDir": "dist",
            "rootDir": ".",
            "skipLibCheck": true,
            "strict": true,
            "target": "ES2022",
            "typeRoots": [type_roots],
            "types": ["node"]
        },
        "include": ["**/*.ts"]
    });
    fs::write(
        staging.path().join("tsconfig.json"),
        format!(
            "{}\n",
            serde_json::to_string_pretty(&tsconfig).map_err(|error| error.to_string())?
        ),
    )
    .map_err(|error| format!("write TypeScript runtime tsconfig: {error}"))?;

    let tsc = repository
        .join("apps/starweaver-desktop/node_modules/.bin")
        .join(if cfg!(windows) { "tsc.CMD" } else { "tsc" });
    if !tsc.is_file() {
        return Err(format!(
            "pinned Desktop TypeScript compiler is unavailable at {}; run corepack pnpm install --frozen-lockfile",
            tsc.display()
        ));
    }
    let mut typecheck = if cfg!(windows) {
        let mut command = Command::new("cmd");
        command.args(["/C"]).arg(&tsc);
        command
    } else {
        Command::new(&tsc)
    };
    let output = typecheck
        .args(["--pretty", "false", "-p", "tsconfig.json"])
        .current_dir(staging.path())
        .output()
        .map_err(|error| format!("start pinned TypeScript compiler: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "generated complete TypeScript bindings failed strict compilation: {}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let output = Command::new("node")
        .arg("dist/validator-runtime-test.js")
        .current_dir(staging.path())
        .output()
        .map_err(|error| format!("start generated TypeScript validator runtime: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "generated complete TypeScript validator runtime rejected its gate: {}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    Ok(())
}

fn request_corpus(repository: &Path, relative: &str) -> Result<Vec<Value>, String> {
    let directory = repository.join(relative);
    let mut paths = fs::read_dir(&directory)
        .map_err(|error| format!("read {}: {error}", directory.display()))?
        .map(|entry| {
            entry
                .map(|entry| entry.path())
                .map_err(|error| error.to_string())
        })
        .collect::<Result<Vec<_>, _>>()?;
    paths.retain(|path| path.extension().and_then(|value| value.to_str()) == Some("json"));
    paths.sort();
    paths
        .into_iter()
        .map(|path| {
            let request: Value = serde_json::from_slice(
                &fs::read(&path)
                    .map_err(|error| format!("read {}: {error}", path.display()))?,
            )
            .map_err(|error| format!("parse {}: {error}", path.display()))?;
            if request.get("method").and_then(Value::as_str).is_none()
                || !request.get("params").is_some_and(Value::is_object)
            {
                return Err(format!(
                    "TypeScript request fixture {} requires method and object params",
                    path.display()
                ));
            }
            Ok(json!({
                "path": path.strip_prefix(repository).unwrap_or(&path).to_string_lossy().replace('\\', "/"),
                "request": request,
            }))
        })
        .collect()
}

pub fn check_source(args: &[String]) -> Result<(), String> {
    no_args(args, "check-rpc-idl-source")?;
    let repository = root()?;
    let protocol_root = repository.join("protocol/host");
    let bundled = bundle::build(&protocol_root)?;
    let ir = ProtocolIr::from_bundle(&bundled.value)?;
    lint::check(&ir)?;
    println!(
        "validated {} methods, {} schemas, {} errors, digest {}",
        ir.methods.len(),
        ir.schemas.len(),
        ir.errors.len(),
        ir.identity.schema_digest
    );
    Ok(())
}

fn render_manifest(
    ir: &ProtocolIr,
    sources: &BTreeMap<String, String>,
    outputs: &BTreeMap<PathBuf, Vec<u8>>,
) -> Result<Vec<u8>, String> {
    let hashes = outputs
        .iter()
        .map(|(path, bytes)| {
            (
                path.to_string_lossy().replace('\\', "/"),
                Value::String(format!("sha256:{:x}", Sha256::digest(bytes))),
            )
        })
        .collect::<serde_json::Map<_, _>>();
    let value = json!({
        "schema": "starweaver.host.generated-manifest",
        "generatorVersion": 1,
        "protocol": {"name": ir.identity.name, "major": ir.identity.major, "revision": ir.identity.revision, "schemaDigest": ir.identity.schema_digest},
        "sources": sources,
        "outputs": hashes,
        "symbols": {"schemas": ir.schemas.len(), "methods": ir.methods.len(), "errors": ir.errors.len(), "notifications": ir.notifications.len()},
    });
    Ok(format!(
        "{}\n",
        serde_json::to_string_pretty(&sort_value(&value)).map_err(|error| error.to_string())?
    )
    .into_bytes())
}

fn format_desktop_outputs(
    repository: &Path,
    files: &mut BTreeMap<PathBuf, Vec<u8>>,
) -> Result<(), String> {
    let staging = tempfile::tempdir().map_err(|error| error.to_string())?;
    let mut desktop_format_paths = Vec::new();
    for (relative, bytes) in files.iter() {
        let staged = staging.path().join(relative);
        if let Some(parent) = staged.parent() {
            fs::create_dir_all(parent).map_err(|error| error.to_string())?;
        }
        fs::write(&staged, bytes)
            .map_err(|error| format!("write formatter input {}: {error}", staged.display()))?;
        let extension = relative.extension().and_then(|value| value.to_str());
        if relative.starts_with("apps/starweaver-desktop")
            && matches!(extension, Some("ts" | "json"))
        {
            desktop_format_paths.push(staged);
        }
    }
    if desktop_format_paths.is_empty() {
        return Ok(());
    }
    {
        let staged_desktop = staging.path().join("apps/starweaver-desktop");
        fs::copy(
            repository.join("apps/starweaver-desktop/biome.json"),
            staged_desktop.join("biome.json"),
        )
        .map_err(|error| format!("stage Desktop Biome config: {error}"))?;
        let relative_desktop_paths = desktop_format_paths
            .iter()
            .map(|path| {
                path.strip_prefix(&staged_desktop)
                    .map(Path::to_path_buf)
                    .map_err(|error| error.to_string())
            })
            .collect::<Result<Vec<_>, _>>()?;
        let desktop_biome = repository
            .join("apps/starweaver-desktop/node_modules/.bin")
            .join(if cfg!(windows) { "biome.CMD" } else { "biome" });
        if !desktop_biome.is_file() {
            return Err(format!(
                "pinned Desktop Biome executable is unavailable at {}; run corepack pnpm install --frozen-lockfile",
                desktop_biome.display()
            ));
        }
        let mut desktop_command = if cfg!(windows) {
            let mut command = Command::new("cmd");
            command.args(["/C"]).arg(&desktop_biome);
            command
        } else {
            Command::new(&desktop_biome)
        };
        let output = desktop_command
            .args(["format", "--write"])
            .args(&relative_desktop_paths)
            .current_dir(&staged_desktop)
            .output()
            .map_err(|error| format!("start pinned Desktop Biome formatter: {error}"))?;
        if !output.status.success() {
            return Err(format!(
                "generated Desktop TypeScript failed Biome formatting: {}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            ));
        }
        // Biome's `expand: auto` can retain an expanded layout on the first
        // pass over a one-line generated declaration. A second pinned pass
        // reaches the stable formatting fixed point used by `biome format .`.
        let output = desktop_command
            .output()
            .map_err(|error| format!("rerun pinned Desktop Biome formatter: {error}"))?;
        if !output.status.success() {
            return Err(format!(
                "generated Desktop TypeScript failed stable Biome formatting: {}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            ));
        }
    }
    for staged in desktop_format_paths {
        let relative = staged
            .strip_prefix(staging.path())
            .map_err(|error| error.to_string())?;
        files.insert(
            relative.to_path_buf(),
            fs::read(&staged)
                .map_err(|error| format!("read formatted {}: {error}", staged.display()))?,
        );
    }
    Ok(())
}

fn generator_owned_files(repository: &Path) -> Result<BTreeSet<PathBuf>, String> {
    let mut files = BTreeSet::new();
    for root in EXCLUSIVE_GENERATED_ROOTS {
        collect_files(repository, Path::new(root), &mut files, |_| Ok(true))?;
    }
    collect_files(
        repository,
        Path::new(AUTOGENERATED_PERMISSIONS_ROOT),
        &mut files,
        |path| file_contains(path, RPC_IDL_GENERATED_MARKER),
    )?;
    collect_files(
        repository,
        Path::new(CAPABILITIES_ROOT),
        &mut files,
        |path| {
            let relative = path
                .strip_prefix(repository)
                .map_err(|error| error.to_string())?;
            Ok(relative == Path::new(GENERATED_HOST_CAPABILITY)
                || file_contains(path, RPC_IDL_CAPABILITY_MARKER)?)
        },
    )?;
    Ok(files)
}

fn collect_files(
    repository: &Path,
    relative: &Path,
    files: &mut BTreeSet<PathBuf>,
    owns: impl Copy + Fn(&Path) -> Result<bool, String>,
) -> Result<(), String> {
    let directory = repository.join(relative);
    let metadata = match fs::symlink_metadata(&directory) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(format!("inspect {}: {error}", directory.display())),
    };
    if !metadata.file_type().is_dir() {
        if owns(&directory)? {
            files.insert(relative.to_path_buf());
        }
        return Ok(());
    }
    for entry in fs::read_dir(&directory)
        .map_err(|error| format!("read {}: {error}", directory.display()))?
    {
        let entry = entry.map_err(|error| format!("read {}: {error}", directory.display()))?;
        let path = entry.path();
        let child_relative = path
            .strip_prefix(repository)
            .map_err(|error| error.to_string())?;
        let file_type = entry
            .file_type()
            .map_err(|error| format!("inspect {}: {error}", path.display()))?;
        if file_type.is_dir() {
            collect_files(repository, child_relative, files, owns)?;
        } else if owns(&path)? {
            files.insert(child_relative.to_path_buf());
        }
    }
    Ok(())
}

fn file_contains(path: &Path, marker: &[u8]) -> Result<bool, String> {
    let bytes = fs::read(path).map_err(|error| format!("read {}: {error}", path.display()))?;
    Ok(bytes.windows(marker.len()).any(|window| window == marker))
}

fn display_paths(paths: &[&PathBuf]) -> String {
    paths
        .iter()
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn path_exists(path: &Path) -> Result<bool, String> {
    match fs::symlink_metadata(path) {
        Ok(_) => Ok(true),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(format!("inspect {}: {error}", path.display())),
    }
}

fn backup_path(target: &Path, index: usize) -> Result<PathBuf, String> {
    let name = target
        .file_name()
        .ok_or_else(|| format!("generated output has no file name: {}", target.display()))?
        .to_string_lossy();
    let backup = target.with_file_name(format!(
        "{name}.starweaver-backup-{}-{index}",
        std::process::id()
    ));
    if path_exists(&backup)? {
        Err(format!(
            "refusing to overwrite promotion backup {}",
            backup.display()
        ))
    } else {
        Ok(backup)
    }
}

fn remove_path(path: &Path) -> std::io::Result<()> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error),
    };
    if metadata.file_type().is_dir() {
        fs::remove_dir_all(path)
    } else {
        fs::remove_file(path)
    }
}

fn rollback(journal: &[(PathBuf, Option<PathBuf>)]) {
    for (target, backup) in journal.iter().rev() {
        let _ = remove_path(target);
        if let Some(backup) = backup {
            let _ = fs::rename(backup, target);
        }
    }
}

fn no_args(args: &[String], command: &str) -> Result<(), String> {
    if args.is_empty() {
        Ok(())
    } else {
        Err(format!("{command} takes no arguments"))
    }
}
