#![allow(
    clippy::format_push_string,
    clippy::literal_string_with_formatting_args,
    clippy::needless_pass_by_value
)]

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    io::Write as _,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use serde::Deserialize;
use serde_json::Value;

use super::model::{ObjectSchema, ProtocolIr, SchemaKind, StringSchema};

const MANIFEST_PATH: &str = "apps/starweaver-desktop/host-bridge/manifest.yaml";
const MANIFEST_SCHEMA: &str = "./manifest.schema.json";
const EXECUTE_COMMAND: &str = "execute_host_operation";
const ACKNOWLEDGE_COMMAND: &str = "acknowledge_host_event";
const ACKNOWLEDGE_OPERATION_COMMAND: &str = "acknowledge_host_operation";
const LIST_PENDING_OPERATIONS_COMMAND: &str = "list_pending_host_operations";
const SUBSCRIBE_COMMAND: &str = "subscribe_host_events";
const UNSUBSCRIBE_COMMAND: &str = "unsubscribe_host_events";
const MAX_INLINE_SCHEMA_DEPTH: usize = 32;

const REQUIRED_DESKTOP_METHODS: &[&str] = &[
    "approval.decide",
    "approval.list",
    "approval.show",
    "catalog.list",
    "clarification.resolve",
    "deferred.complete",
    "deferred.fail",
    "deferred.list",
    "deferred.show",
    "environment.detach",
    "environment.health",
    "environment.list",
    "model.select",
    "model.selection.get",
    "profile.get",
    "run.interrupt",
    "run.resume",
    "run.start",
    "run.status",
    "run.steer",
    "session.create",
    "session.delete",
    "session.fork",
    "session.get",
    "session.list",
    "session.search",
];

const DESKTOP_EVENT_KINDS: &[&str] = &[
    "approval_changed",
    "clarification_changed",
    "deferred_changed",
    "output_available",
    "run_changed",
];

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
struct SurfaceManifest {
    #[serde(rename = "$schema")]
    schema: String,
    schema_version: u32,
    protocol: SurfaceProtocol,
    commands: SurfaceCommands,
    renderer_input_variants: BTreeMap<String, Vec<String>>,
    operations: BTreeMap<String, SurfaceOperation>,
    notifications: BTreeMap<String, SurfaceNotification>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SurfaceProtocol {
    name: String,
    major: u32,
    digest: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
struct SurfaceCommands {
    acknowledge: String,
    acknowledge_operation: String,
    execute: String,
    list_pending_operations: String,
    subscribe: String,
    unsubscribe: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SurfaceOperation {
    input: InputAuthority,
    output: OutputAuthority,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
struct InputAuthority {
    renderer_provided: Vec<String>,
    supervisor_constructed: Vec<String>,
    supervisor_overridden: Vec<String>,
    forbidden: Vec<String>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct OutputAuthority {
    select: Vec<String>,
    transform: Vec<String>,
    forbidden: Vec<String>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SurfaceNotification {
    profile: String,
    projection: String,
    output: OutputAuthority,
}

pub fn generate(repository: &Path, ir: &ProtocolIr) -> Result<BTreeMap<PathBuf, Vec<u8>>, String> {
    let manifest = load_manifest(repository)?;
    validate_manifest(ir, &manifest)?;

    let mut outputs = BTreeMap::new();
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src/generated/host/types.ts",
        render_typescript_types(ir, &manifest)?,
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src/generated/host/validators.ts",
        render_typescript_validators(ir, &manifest),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src/generated/host/client.ts",
        render_typescript_client(&manifest),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src/generated/host/index.ts",
        render_typescript_index(),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src-tauri/src/generated/host/mod.rs",
        rustfmt_source(&render_rust(ir, &manifest)?)?,
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src-tauri/permissions/autogenerated/acknowledge_host_event.toml",
        render_permission(
            ACKNOWLEDGE_COMMAND,
            "Acknowledge one supervisor-issued Desktop host event delivery",
        ),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src-tauri/permissions/autogenerated/acknowledge_host_operation.toml",
        render_permission(
            ACKNOWLEDGE_OPERATION_COMMAND,
            "Acknowledge one supervisor-issued Desktop host operation result",
        ),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src-tauri/permissions/autogenerated/list_pending_host_operations.toml",
        render_permission(
            LIST_PENDING_OPERATIONS_COMMAND,
            "List unresolved renderer-safe Desktop host operation handles",
        ),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src-tauri/permissions/autogenerated/execute_host_operation.toml",
        render_permission(
            EXECUTE_COMMAND,
            "Execute one generated renderer-safe host operation",
        ),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src-tauri/permissions/autogenerated/subscribe_host_events.toml",
        render_permission(
            SUBSCRIBE_COMMAND,
            "Subscribe to generated renderer-safe host events",
        ),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src-tauri/permissions/autogenerated/unsubscribe_host_events.toml",
        render_permission(
            UNSUBSCRIBE_COMMAND,
            "Unsubscribe a supervisor-issued host event token",
        ),
    );
    insert(
        &mut outputs,
        "apps/starweaver-desktop/src-tauri/capabilities/generated-host.json",
        render_capability_fragment(ir, &manifest)?,
    );
    Ok(outputs)
}

#[allow(dead_code)]
pub fn validate_manifest_value(ir: &ProtocolIr, value: Value) -> Result<(), String> {
    let manifest: SurfaceManifest = serde_json::from_value(value)
        .map_err(|error| format!("invalid Desktop host-surface manifest: {error}"))?;
    validate_manifest(ir, &manifest)
}

fn load_manifest(repository: &Path) -> Result<SurfaceManifest, String> {
    let path = repository.join(MANIFEST_PATH);
    let value = super::source::load_yaml(&path)?;
    let schema_path = path
        .parent()
        .ok_or_else(|| format!("{} has no parent", path.display()))?
        .join("manifest.schema.json");
    let schema: Value = serde_json::from_slice(
        &fs::read(&schema_path)
            .map_err(|error| format!("read {}: {error}", schema_path.display()))?,
    )
    .map_err(|error| format!("parse {}: {error}", schema_path.display()))?;
    let validator = jsonschema::options()
        .with_draft(jsonschema::Draft::Draft7)
        .build(&schema)
        .map_err(|error| format!("compile {}: {error}", schema_path.display()))?;
    if let Err(error) = validator.validate(&value) {
        return Err(format!(
            "{} rejected Desktop host surface: {error}",
            schema_path.display()
        ));
    }
    serde_json::from_value(value)
        .map_err(|error| format!("parse {} as typed manifest: {error}", path.display()))
}

fn validate_manifest(ir: &ProtocolIr, manifest: &SurfaceManifest) -> Result<(), String> {
    if manifest.schema != MANIFEST_SCHEMA || manifest.schema_version != 1 {
        return Err("Desktop host surface must use the reviewed schema version 1".to_string());
    }
    if manifest.protocol.name != ir.identity.name || manifest.protocol.major != ir.identity.major {
        return Err("Desktop host surface protocol identity does not match ProtocolIr".to_string());
    }
    if manifest.protocol.digest != ir.identity.schema_digest {
        return Err(format!(
            "Desktop host surface digest must match the reviewed protocol digest {}",
            ir.identity.schema_digest
        ));
    }
    if manifest.commands.acknowledge != ACKNOWLEDGE_COMMAND
        || manifest.commands.acknowledge_operation != ACKNOWLEDGE_OPERATION_COMMAND
        || manifest.commands.execute != EXECUTE_COMMAND
        || manifest.commands.list_pending_operations != LIST_PENDING_OPERATIONS_COMMAND
        || manifest.commands.subscribe != SUBSCRIBE_COMMAND
        || manifest.commands.unsubscribe != UNSUBSCRIBE_COMMAND
    {
        return Err(
            "Desktop host surface command names are not the fixed reviewed commands".to_string(),
        );
    }

    validate_renderer_input_variants(ir, manifest)?;

    let expected = REQUIRED_DESKTOP_METHODS
        .iter()
        .map(|value| (*value).to_string())
        .collect::<BTreeSet<_>>();
    let actual = manifest.operations.keys().cloned().collect::<BTreeSet<_>>();
    if actual != expected {
        return Err(format!(
            "Desktop operation inventory mismatch: missing {:?}, unexpected {:?}",
            expected.difference(&actual).collect::<Vec<_>>(),
            actual.difference(&expected).collect::<Vec<_>>()
        ));
    }

    for (name, surface) in &manifest.operations {
        let method = ir
            .methods
            .get(name)
            .ok_or_else(|| format!("Desktop operation {name} is not a public IDL method"))?;
        let params = object_schema(ir, &method.params_type)?;
        validate_input_authority(
            ir,
            name,
            params,
            &surface.input,
            &manifest.renderer_input_variants,
        )?;
        let result = object_schema(ir, &method.result_type)?;
        validate_output_authority(ir, name, result, &surface.output)?;
    }

    if manifest.notifications.len() != 1 || !manifest.notifications.contains_key("host.event") {
        return Err(
            "Desktop surface must expose exactly the canonical host.event notification".to_string(),
        );
    }
    for (name, surface) in &manifest.notifications {
        let notification = ir
            .notifications
            .get(name)
            .ok_or_else(|| format!("Desktop notification {name} is not public IDL"))?;
        let params = object_schema(ir, &notification.params_type)?;
        validate_output_authority(ir, name, params, &surface.output)?;
        let profile = ir.event_profiles.get(&surface.profile).ok_or_else(|| {
            format!(
                "Desktop notification {name} has unknown profile {}",
                surface.profile
            )
        })?;
        let allowed = DESKTOP_EVENT_KINDS.iter().copied().collect::<BTreeSet<_>>();
        for event_kind in profile {
            if !allowed.contains(event_kind.as_str()) {
                return Err(format!(
                    "Desktop profile {} contains unauthorized event kind {event_kind}",
                    surface.profile
                ));
            }
        }
        if surface.projection.is_empty()
            || !surface
                .projection
                .starts_with(|character: char| character.is_ascii_uppercase())
        {
            return Err(format!(
                "Desktop notification {name} has invalid projection name"
            ));
        }
    }
    Ok(())
}

fn validate_renderer_input_variants(
    ir: &ProtocolIr,
    manifest: &SurfaceManifest,
) -> Result<(), String> {
    for (schema_name, allowed_variants) in &manifest.renderer_input_variants {
        let schema = ir
            .schemas
            .get(schema_name)
            .ok_or_else(|| format!("unknown renderer input union {schema_name}"))?;
        let SchemaKind::OneOf { variants, .. } = &schema.kind else {
            return Err(format!(
                "renderer input variant policy target {schema_name} is not a union"
            ));
        };
        let available = variants
            .iter()
            .filter_map(|variant| match variant {
                SchemaKind::Ref(name) => Some(name.as_str()),
                _ => None,
            })
            .collect::<BTreeSet<_>>();
        if available.len() != variants.len() {
            return Err(format!(
                "renderer input union {schema_name} must contain only named variants"
            ));
        }
        let allowed = allowed_variants
            .iter()
            .map(String::as_str)
            .collect::<BTreeSet<_>>();
        if allowed.is_empty()
            || allowed.len() != allowed_variants.len()
            || !allowed.is_subset(&available)
        {
            return Err(format!(
                "renderer input union {schema_name} has an invalid variant allowlist"
            ));
        }
    }
    Ok(())
}

fn validate_input_authority(
    ir: &ProtocolIr,
    operation: &str,
    schema: &ObjectSchema,
    authority: &InputAuthority,
    renderer_input_variants: &BTreeMap<String, Vec<String>>,
) -> Result<(), String> {
    let groups = [
        ("rendererProvided", &authority.renderer_provided),
        ("supervisorConstructed", &authority.supervisor_constructed),
        ("supervisorOverridden", &authority.supervisor_overridden),
        ("forbidden", &authority.forbidden),
    ];
    validate_partition(operation, schema.properties.keys(), &groups)?;
    for field in &authority.renderer_provided {
        if is_supervisor_owned_name(field) {
            return Err(format!(
                "Desktop renderer cannot own supervisor field {operation}.{field}"
            ));
        }
        let kind = schema
            .properties
            .get(field)
            .ok_or_else(|| format!("missing field {operation}.{field}"))?;
        ensure_renderer_input_safe(
            ir,
            kind,
            renderer_input_variants,
            &format!("{operation}.{field}"),
            0,
            &mut BTreeSet::new(),
        )?;
    }
    for field in &authority.forbidden {
        if schema.required.contains(field) {
            return Err(format!(
                "required field {operation}.{field} cannot be forbidden because complete params could not be built"
            ));
        }
    }
    Ok(())
}

fn validate_output_authority(
    ir: &ProtocolIr,
    symbol: &str,
    schema: &ObjectSchema,
    authority: &OutputAuthority,
) -> Result<(), String> {
    let groups = [
        ("select", &authority.select),
        ("transform", &authority.transform),
        ("forbidden", &authority.forbidden),
    ];
    validate_partition(symbol, schema.properties.keys(), &groups)?;
    for field in &authority.select {
        let kind = schema
            .properties
            .get(field)
            .ok_or_else(|| format!("missing output field {symbol}.{field}"))?;
        ensure_direct_output_safe(
            ir,
            kind,
            &format!("{symbol}.{field}"),
            0,
            &mut BTreeSet::new(),
        )?;
    }
    for field in &authority.transform {
        let kind = schema
            .properties
            .get(field)
            .ok_or_else(|| format!("missing transformed output field {symbol}.{field}"))?;
        ensure_transformed_output_safe(
            ir,
            kind,
            &format!("{symbol}.{field}"),
            0,
            &mut BTreeSet::new(),
        )?;
    }
    Ok(())
}

fn validate_partition<'a>(
    symbol: &str,
    fields: impl Iterator<Item = &'a String>,
    groups: &[(&str, &Vec<String>)],
) -> Result<(), String> {
    let expected = fields.cloned().collect::<BTreeSet<_>>();
    let mut classified = BTreeMap::<String, String>::new();
    for (group, values) in groups {
        let mut local = BTreeSet::new();
        for field in *values {
            if !local.insert(field) {
                return Err(format!("{symbol}.{field} is duplicated in {group}"));
            }
            if let Some(previous) = classified.insert(field.clone(), (*group).to_string()) {
                return Err(format!(
                    "{symbol}.{field} belongs to both {previous} and {group}"
                ));
            }
        }
    }
    let actual = classified.keys().cloned().collect::<BTreeSet<_>>();
    if actual != expected {
        return Err(format!(
            "field authority for {symbol} is incomplete: missing {:?}, unknown {:?}",
            expected.difference(&actual).collect::<Vec<_>>(),
            actual.difference(&expected).collect::<Vec<_>>()
        ));
    }
    Ok(())
}

fn ensure_renderer_input_safe(
    ir: &ProtocolIr,
    kind: &SchemaKind,
    renderer_input_variants: &BTreeMap<String, Vec<String>>,
    path: &str,
    depth: usize,
    visiting: &mut BTreeSet<String>,
) -> Result<(), String> {
    if depth > MAX_INLINE_SCHEMA_DEPTH {
        return Err(format!("renderer schema exceeds depth limit at {path}"));
    }
    match kind {
        SchemaKind::Ref(name) => {
            if is_forbidden_schema_name(name) {
                return Err(format!(
                    "renderer field {path} references forbidden schema {name}"
                ));
            }
            if !visiting.insert(name.clone()) {
                return Err(format!(
                    "renderer field {path} contains recursive schema {name}"
                ));
            }
            let schema = ir
                .schemas
                .get(name)
                .ok_or_else(|| format!("unknown schema {name} at {path}"))?;
            if let Some(allowed) = renderer_input_variants.get(name) {
                let SchemaKind::OneOf { variants, .. } = &schema.kind else {
                    return Err(format!(
                        "renderer input variant target {name} is not a union"
                    ));
                };
                for variant in variants.iter().filter(|variant| {
                    matches!(variant, SchemaKind::Ref(target) if allowed.contains(target))
                }) {
                    ensure_renderer_input_safe(
                        ir,
                        variant,
                        renderer_input_variants,
                        path,
                        depth + 1,
                        visiting,
                    )?;
                }
            } else {
                ensure_renderer_input_safe(
                    ir,
                    &schema.kind,
                    renderer_input_variants,
                    path,
                    depth + 1,
                    visiting,
                )?;
            }
            visiting.remove(name);
        }
        SchemaKind::JsonObject => {
            return Err(format!(
                "renderer field {path} cannot contain an arbitrary JSON object"
            ));
        }
        SchemaKind::Object(object) => {
            for (field, value) in &object.properties {
                if is_sensitive_name(field) {
                    return Err(format!("renderer field {path}.{field} is sensitive"));
                }
                ensure_renderer_input_safe(
                    ir,
                    value,
                    renderer_input_variants,
                    &format!("{path}.{field}"),
                    depth + 1,
                    visiting,
                )?;
            }
        }
        SchemaKind::Array { items, .. } => {
            ensure_renderer_input_safe(
                ir,
                items,
                renderer_input_variants,
                path,
                depth + 1,
                visiting,
            )?;
        }
        SchemaKind::OneOf { variants, .. } => {
            for variant in variants {
                ensure_renderer_input_safe(
                    ir,
                    variant,
                    renderer_input_variants,
                    path,
                    depth + 1,
                    visiting,
                )?;
            }
        }
        SchemaKind::String(_)
        | SchemaKind::Integer { .. }
        | SchemaKind::Boolean
        | SchemaKind::Null => {}
    }
    Ok(())
}

fn ensure_direct_output_safe(
    ir: &ProtocolIr,
    kind: &SchemaKind,
    path: &str,
    depth: usize,
    visiting: &mut BTreeSet<String>,
) -> Result<(), String> {
    if depth > MAX_INLINE_SCHEMA_DEPTH {
        return Err(format!("selected output exceeds depth limit at {path}"));
    }
    match kind {
        SchemaKind::Ref(name) => {
            if is_forbidden_schema_name(name) {
                return Err(format!(
                    "selected output {path} references forbidden schema {name}"
                ));
            }
            if !visiting.insert(name.clone()) {
                return Err(format!(
                    "selected output {path} contains recursive schema {name}"
                ));
            }
            let schema = ir
                .schemas
                .get(name)
                .ok_or_else(|| format!("unknown schema {name} at {path}"))?;
            ensure_direct_output_safe(ir, &schema.kind, path, depth + 1, visiting)?;
            visiting.remove(name);
        }
        SchemaKind::JsonObject => {
            return Err(format!(
                "selected output {path} cannot expose an arbitrary JSON object"
            ));
        }
        SchemaKind::Object(object) => {
            for (field, value) in &object.properties {
                if is_sensitive_name(field) {
                    return Err(format!("selected output {path}.{field} is sensitive"));
                }
                ensure_direct_output_safe(
                    ir,
                    value,
                    &format!("{path}.{field}"),
                    depth + 1,
                    visiting,
                )?;
            }
        }
        SchemaKind::Array { items, .. } => {
            ensure_direct_output_safe(ir, items, path, depth + 1, visiting)?;
        }
        SchemaKind::OneOf { variants, .. } => {
            for variant in variants {
                ensure_direct_output_safe(ir, variant, path, depth + 1, visiting)?;
            }
        }
        SchemaKind::String(_)
        | SchemaKind::Integer { .. }
        | SchemaKind::Boolean
        | SchemaKind::Null => {}
    }
    Ok(())
}

fn ensure_transformed_output_safe(
    ir: &ProtocolIr,
    kind: &SchemaKind,
    path: &str,
    depth: usize,
    visiting: &mut BTreeSet<String>,
) -> Result<(), String> {
    if depth > MAX_INLINE_SCHEMA_DEPTH {
        return Err(format!("transformed output exceeds depth limit at {path}"));
    }
    match kind {
        SchemaKind::Ref(name) => {
            if !visiting.insert(name.clone()) {
                return Err(format!(
                    "transformed output {path} contains recursive schema {name}"
                ));
            }
            let schema = ir
                .schemas
                .get(name)
                .ok_or_else(|| format!("unknown schema {name} at {path}"))?;
            ensure_transformed_output_safe(ir, &schema.kind, path, depth + 1, visiting)?;
            visiting.remove(name);
        }
        SchemaKind::JsonObject => {
            return Err(format!(
                "transformed output {path} cannot expose an arbitrary JSON object"
            ));
        }
        SchemaKind::Object(object) => {
            for (field, value) in &object.properties {
                if is_forbidden_projected_field(field) {
                    continue;
                }
                if is_transformed_output_sensitive_name(field) {
                    return Err(format!(
                        "transformed output {path}.{field} is sensitive but is not removed by the generated projector"
                    ));
                }
                ensure_transformed_output_safe(
                    ir,
                    value,
                    &format!("{path}.{field}"),
                    depth + 1,
                    visiting,
                )?;
            }
        }
        SchemaKind::Array { items, .. } => {
            ensure_transformed_output_safe(ir, items, path, depth + 1, visiting)?;
        }
        SchemaKind::OneOf { variants, .. } => {
            for variant in variants {
                ensure_transformed_output_safe(ir, variant, path, depth + 1, visiting)?;
            }
        }
        SchemaKind::String(_)
        | SchemaKind::Integer { .. }
        | SchemaKind::Boolean
        | SchemaKind::Null => {}
    }
    Ok(())
}

fn is_supervisor_owned_name(name: &str) -> bool {
    matches!(
        compact_name(name).as_str(),
        "requestid"
            | "idempotencykey"
            | "scope"
            | "clientscope"
            | "authorityscope"
            | "route"
            | "routingoverride"
            | "path"
            | "executiondomain"
            | "workspaceroot"
    )
}

fn is_transformed_output_sensitive_name(name: &str) -> bool {
    let value = compact_name(name);
    value.contains("credential")
        || value.contains("secret")
        || value.contains("password")
        || value.contains("privatekey")
        || value.contains("authorization")
        || value.contains("rawpath")
        || value == "path"
        || value == "uri"
        || value == "scope"
        || value.contains("routingoverride")
        || value.contains("executiondomain")
}

fn is_sensitive_name(name: &str) -> bool {
    let value = compact_name(name);
    value.contains("credential")
        || value.contains("secret")
        || value.contains("password")
        || value.contains("privatekey")
        || value.contains("authorization")
        || value.contains("header")
        || value.contains("rawpath")
        || value == "path"
        || value == "uri"
        || value == "scope"
        || value.contains("routingoverride")
        || value.contains("executiondomain")
}

fn is_forbidden_schema_name(name: &str) -> bool {
    let value = compact_name(name);
    value == "jsonvalue"
        || value.contains("credential")
        || value.contains("secret")
        || value.contains("diagnostic")
        || value.contains("privatepath")
        || value.contains("authorityscope")
        || value.contains("routingoverride")
}

fn compact_name(value: &str) -> String {
    value
        .chars()
        .filter(char::is_ascii_alphanumeric)
        .flat_map(char::to_lowercase)
        .collect()
}

fn object_schema<'a>(ir: &'a ProtocolIr, name: &str) -> Result<&'a ObjectSchema, String> {
    let schema = ir
        .schemas
        .get(name)
        .ok_or_else(|| format!("unknown object schema {name}"))?;
    match &schema.kind {
        SchemaKind::Object(object) => Ok(object),
        _ => Err(format!("schema {name} must be a closed object")),
    }
}

fn render_typescript_types(ir: &ProtocolIr, manifest: &SurfaceManifest) -> Result<String, String> {
    let mut out = generated_ts_header(ir);
    out.push_str("declare const desktopEmptyIntent: unique symbol;\n");
    out.push_str("export type DesktopHostSubscriptionToken = string & { readonly __desktopHostSubscriptionToken: unique symbol };\n");
    out.push_str("export type DesktopHostEventAcknowledgementToken = string & { readonly __desktopHostEventAcknowledgementToken: unique symbol };\n");
    out.push_str("export type DesktopHostOperationAcknowledgementToken = string & { readonly __desktopHostOperationAcknowledgementToken: unique symbol };\n");
    out.push_str("export type DesktopOperationId = string & { readonly __desktopOperationId: unique symbol };\n");
    out.push_str(
        "export type DesktopPageToken = string & { readonly __desktopPageToken: unique symbol };\n",
    );
    out.push_str("export type DesktopPage = { readonly hasMore: boolean; readonly nextPageToken?: DesktopPageToken };\n");
    out.push_str("export type DesktopHostEventScope = { readonly sessionId: string; readonly runId: string };\n\n");
    for (name, surface) in &manifest.operations {
        let method = &ir.methods[name];
        let params = object_schema(ir, &method.params_type)?;
        let result = object_schema(ir, &method.result_type)?;
        let base = pascal(name);
        let paginated = is_paginated(surface);
        if surface.input.renderer_provided.is_empty() && !paginated {
            out.push_str(&format!(
                "export type {base}Intent = {{ readonly [desktopEmptyIntent]?: never }};\n"
            ));
        } else {
            out.push_str(&format!("export type {base}Intent = {{\n"));
            for field in &surface.input.renderer_provided {
                let kind = &params.properties[field];
                let optional = if params.required.contains(field) {
                    ""
                } else {
                    "?"
                };
                out.push_str(&format!(
                    "  readonly {}{}: {};\n",
                    ts_property(field),
                    optional,
                    renderer_ts_type(
                        ir,
                        kind,
                        &manifest.renderer_input_variants,
                        0,
                        &mut BTreeSet::new(),
                    )?
                ));
            }
            if paginated {
                out.push_str("  readonly pageToken?: DesktopPageToken;\n");
            }
            out.push_str("};\n");
        }
        out.push_str(&format!("export type {base}Result = {{\n"));
        for field in &surface.output.select {
            out.push_str(&format!(
                "  readonly {}: {};\n",
                ts_property(field),
                ts_type(ir, &result.properties[field], 0, &mut BTreeSet::new())?
            ));
        }
        for field in &surface.output.transform {
            let field_type = if field == "page" && is_paginated(surface) {
                "DesktopPage".to_string()
            } else {
                safe_ts_type(ir, &result.properties[field], 0, &mut BTreeSet::new())?
            };
            out.push_str(&format!(
                "  readonly {}: {};\n",
                ts_property(field),
                field_type
            ));
        }
        out.push_str("};\n\n");
    }
    out.push_str("export type DesktopHostOperation =\n");
    for (index, name) in manifest.operations.keys().enumerate() {
        let base = pascal(name);
        out.push_str(&format!(
            "  {} {{ readonly kind: {}; readonly input: {base}Intent }}\n",
            if index == 0 { "" } else { "|" },
            json_string(name)
        ));
    }
    out.push_str(";\n\nexport type DesktopHostInvocation<K extends DesktopHostOperationKind = DesktopHostOperationKind> = { readonly operationId: DesktopOperationId; readonly operation: Extract<DesktopHostOperation, { readonly kind: K }> };\n\nexport interface DesktopHostResultMap {\n");
    for name in manifest.operations.keys() {
        out.push_str(&format!(
            "  readonly {}: {}Result;\n",
            json_string(name),
            pascal(name)
        ));
    }
    out.push_str("}\nexport type DesktopHostOperationKind = keyof DesktopHostResultMap;\n");
    let notification = &manifest.notifications["host.event"];
    out.push_str(&format!("export type {} = {{\n", notification.projection));
    for field in &notification.output.select {
        let params = object_schema(ir, &ir.notifications["host.event"].params_type)?;
        out.push_str(&format!(
            "  readonly {}: {};\n",
            ts_property(field),
            ts_type(ir, &params.properties[field], 0, &mut BTreeSet::new())?
        ));
    }
    for field in &notification.output.transform {
        let params = object_schema(ir, &ir.notifications["host.event"].params_type)?;
        out.push_str(&format!(
            "  readonly {}: {};\n",
            ts_property(field),
            safe_ts_type(ir, &params.properties[field], 0, &mut BTreeSet::new())?
        ));
    }
    out.push_str("};\n");
    out.push_str("export type DesktopHostOperationDelivery = { readonly acknowledgementToken?: DesktopHostOperationAcknowledgementToken; readonly result: DesktopHostResultMap[DesktopHostOperationKind] };\n");
    out.push_str("export type DesktopHostEventDelivery = { readonly acknowledgementToken: DesktopHostEventAcknowledgementToken; readonly event: SafeHostEvent };\n");
    Ok(out)
}

fn renderer_ts_type(
    ir: &ProtocolIr,
    kind: &SchemaKind,
    renderer_input_variants: &BTreeMap<String, Vec<String>>,
    depth: usize,
    visiting: &mut BTreeSet<String>,
) -> Result<String, String> {
    if depth > MAX_INLINE_SCHEMA_DEPTH {
        return Err("Desktop renderer TypeScript type expansion exceeded depth limit".to_string());
    }
    Ok(match kind {
        SchemaKind::Ref(name) => {
            if !visiting.insert(name.clone()) {
                return Err(format!("recursive renderer TypeScript schema {name}"));
            }
            let schema = ir
                .schemas
                .get(name)
                .ok_or_else(|| format!("unknown renderer TypeScript schema {name}"))?;
            let value = if let Some(allowed) = renderer_input_variants.get(name) {
                let SchemaKind::OneOf { variants, .. } = &schema.kind else {
                    return Err(format!(
                        "renderer input variant target {name} is not a union"
                    ));
                };
                variants
                    .iter()
                    .filter(|variant| {
                        matches!(variant, SchemaKind::Ref(target) if allowed.contains(target))
                    })
                    .map(|variant| {
                        renderer_ts_type(
                            ir,
                            variant,
                            renderer_input_variants,
                            depth + 1,
                            visiting,
                        )
                    })
                    .collect::<Result<Vec<_>, _>>()?
                    .join(" | ")
            } else {
                renderer_ts_type(
                    ir,
                    &schema.kind,
                    renderer_input_variants,
                    depth + 1,
                    visiting,
                )?
            };
            visiting.remove(name);
            value
        }
        SchemaKind::String(StringSchema { enum_values, .. }) if !enum_values.is_empty() => {
            enum_values
                .iter()
                .map(|value| json_string(value))
                .collect::<Vec<_>>()
                .join(" | ")
        }
        SchemaKind::String(StringSchema {
            const_value: Some(value),
            ..
        }) => json_string(value),
        SchemaKind::String(_) => "string".to_string(),
        SchemaKind::Integer { .. } => "number".to_string(),
        SchemaKind::Boolean => "boolean".to_string(),
        SchemaKind::Null => "null".to_string(),
        SchemaKind::JsonObject => "Readonly<Record<string, unknown>>".to_string(),
        SchemaKind::Array { items, .. } => format!(
            "readonly ({})[]",
            renderer_ts_type(ir, items, renderer_input_variants, depth + 1, visiting,)?
        ),
        SchemaKind::Object(object) => {
            let mut value = String::from("{ ");
            for (field, field_kind) in &object.properties {
                let optional = if object.required.contains(field) {
                    ""
                } else {
                    "?"
                };
                value.push_str(&format!(
                    "readonly {}{}: {}; ",
                    ts_property(field),
                    optional,
                    renderer_ts_type(ir, field_kind, renderer_input_variants, depth + 1, visiting,)?
                ));
            }
            value.push('}');
            value
        }
        SchemaKind::OneOf { variants, .. } => variants
            .iter()
            .map(|variant| {
                renderer_ts_type(ir, variant, renderer_input_variants, depth + 1, visiting)
            })
            .collect::<Result<Vec<_>, _>>()?
            .join(" | "),
    })
}

fn ts_type(
    ir: &ProtocolIr,
    kind: &SchemaKind,
    depth: usize,
    visiting: &mut BTreeSet<String>,
) -> Result<String, String> {
    if depth > MAX_INLINE_SCHEMA_DEPTH {
        return Err("Desktop TypeScript type expansion exceeded depth limit".to_string());
    }
    Ok(match kind {
        SchemaKind::Ref(name) => {
            if !visiting.insert(name.clone()) {
                return Err(format!("recursive renderer TypeScript schema {name}"));
            }
            let value = ts_type(ir, &ir.schemas[name].kind, depth + 1, visiting)?;
            visiting.remove(name);
            value
        }
        SchemaKind::String(StringSchema {
            enum_values,
            const_value,
            ..
        }) if !enum_values.is_empty() => enum_values
            .iter()
            .map(|value| json_string(value))
            .collect::<Vec<_>>()
            .join(" | "),
        SchemaKind::String(StringSchema {
            const_value: Some(value),
            ..
        }) => json_string(value),
        SchemaKind::String(_) => "string".to_string(),
        SchemaKind::Integer { .. } => "number".to_string(),
        SchemaKind::Boolean => "boolean".to_string(),
        SchemaKind::Null => "null".to_string(),
        SchemaKind::JsonObject => "Readonly<Record<string, unknown>>".to_string(),
        SchemaKind::Array { items, .. } => {
            format!("readonly ({})[]", ts_type(ir, items, depth + 1, visiting)?)
        }
        SchemaKind::Object(object) => {
            let mut value = String::from("{ ");
            for (field, field_kind) in &object.properties {
                let optional = if object.required.contains(field) {
                    ""
                } else {
                    "?"
                };
                value.push_str(&format!(
                    "readonly {}{}: {}; ",
                    ts_property(field),
                    optional,
                    ts_type(ir, field_kind, depth + 1, visiting)?
                ));
            }
            value.push('}');
            value
        }
        SchemaKind::OneOf { variants, .. } => variants
            .iter()
            .map(|variant| ts_type(ir, variant, depth + 1, visiting))
            .collect::<Result<Vec<_>, _>>()?
            .join(" | "),
    })
}

fn safe_ts_type(
    ir: &ProtocolIr,
    kind: &SchemaKind,
    depth: usize,
    visiting: &mut BTreeSet<String>,
) -> Result<String, String> {
    if depth > MAX_INLINE_SCHEMA_DEPTH {
        return Err("Desktop safe projection expansion exceeded depth limit".to_string());
    }
    Ok(match kind {
        SchemaKind::Ref(name) => {
            if !visiting.insert(name.clone()) {
                return Err(format!("recursive Desktop safe projection schema {name}"));
            }
            let value = if name == "HostEvent" {
                let SchemaKind::OneOf { variants, .. } = &ir.schemas[name].kind else {
                    return Err("HostEvent must remain a generated closed union".to_string());
                };
                variants
                    .iter()
                    .filter(|variant| is_desktop_event_variant(ir, variant))
                    .map(|variant| safe_ts_type(ir, variant, depth + 1, visiting))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(" | ")
            } else {
                safe_ts_type(ir, &ir.schemas[name].kind, depth + 1, visiting)?
            };
            visiting.remove(name);
            value
        }
        SchemaKind::String(StringSchema {
            enum_values,
            const_value,
            ..
        }) if !enum_values.is_empty() => enum_values
            .iter()
            .map(|value| json_string(value))
            .collect::<Vec<_>>()
            .join(" | "),
        SchemaKind::String(StringSchema {
            const_value: Some(value),
            ..
        }) => json_string(value),
        SchemaKind::String(_) => "string".to_string(),
        SchemaKind::Integer { .. } => "number".to_string(),
        SchemaKind::Boolean => "boolean".to_string(),
        SchemaKind::Null => "null".to_string(),
        SchemaKind::JsonObject => {
            return Err("arbitrary JSON cannot enter a Desktop safe projection".to_string());
        }
        SchemaKind::Array { items, .. } => format!(
            "readonly ({})[]",
            safe_ts_type(ir, items, depth + 1, visiting)?
        ),
        SchemaKind::Object(object) => {
            let mut value = String::from("{ ");
            for (field, field_kind) in &object.properties {
                if is_forbidden_projected_field(field) {
                    continue;
                }
                let optional = if object.required.contains(field) {
                    ""
                } else {
                    "?"
                };
                value.push_str(&format!(
                    "readonly {}{}: {}; ",
                    ts_property(field),
                    optional,
                    safe_ts_type(ir, field_kind, depth + 1, visiting)?
                ));
            }
            value.push('}');
            value
        }
        SchemaKind::OneOf { variants, .. } => variants
            .iter()
            .map(|variant| safe_ts_type(ir, variant, depth + 1, visiting))
            .collect::<Result<Vec<_>, _>>()?
            .join(" | "),
    })
}

fn is_desktop_event_variant(ir: &ProtocolIr, variant: &SchemaKind) -> bool {
    let SchemaKind::Ref(schema_name) = variant else {
        return false;
    };
    DESKTOP_EVENT_KINDS.iter().any(|event_kind| {
        ir.event_classes
            .get(*event_kind)
            .is_some_and(|class| class.schema_type == *schema_name)
    })
}

fn is_forbidden_projected_field(field: &str) -> bool {
    matches!(
        field,
        "acceptedCursor"
            | "cursor"
            | "deliverySequence"
            | "diagnosticRef"
            | "fenceCursor"
            | "fingerprint"
            | "idempotencyKey"
            | "nextCursor"
            | "nextDeliverySequence"
            | "scope"
            | "subscriptionId"
    )
}

fn render_typescript_validators(ir: &ProtocolIr, manifest: &SurfaceManifest) -> String {
    let mut out = generated_ts_comment(ir);
    out.push_str("import type { DesktopHostEventDelivery, DesktopHostInvocation, DesktopHostOperationAcknowledgementToken, DesktopHostOperationKind, DesktopHostResultMap, DesktopOperationId, SafeHostEvent } from \"./types\";\n\n");
    out.push_str(
        "export class DesktopHostValidationError extends Error {\n  constructor(readonly path: string, message: string) { super(`${path}: ${message}`); this.name = \"DesktopHostValidationError\"; }\n}\n\n",
    );
    out.push_str("function record(value: unknown, path: string): Record<string, unknown> { if (typeof value !== \"object\" || value === null || Array.isArray(value)) throw new DesktopHostValidationError(path, \"expected object\"); return value as Record<string, unknown>; }\n");
    out.push_str("function exact(value: Record<string, unknown>, fields: readonly string[], path: string): void { const allowed = new Set(fields); for (const key of Object.keys(value)) if (!allowed.has(key)) throw new DesktopHostValidationError(`${path}.${key}`, \"unexpected field\"); for (const field of fields) if (!(field in value)) throw new DesktopHostValidationError(`${path}.${field}`, \"missing field\"); }\n");
    out.push_str("const forbiddenProjectedFields = new Set([\"acceptedCursor\", \"cursor\", \"deliverySequence\", \"diagnosticRef\", \"fenceCursor\", \"fingerprint\", \"idempotencyKey\", \"nextCursor\", \"nextDeliverySequence\", \"scope\", \"subscriptionId\"]);\n");
    out.push_str("function projected(value: unknown, path: string): unknown { if (value === null || typeof value === \"string\" || typeof value === \"number\" || typeof value === \"boolean\") return value; if (Array.isArray(value)) return value.map((entry, index) => projected(entry, `${path}[${index}]`)); const item = record(value, path); const result: Record<string, unknown> = {}; for (const [key, entry] of Object.entries(item)) { if (forbiddenProjectedFields.has(key)) throw new DesktopHostValidationError(`${path}.${key}`, \"supervisor-owned field crossed projection\"); result[key] = projected(entry, `${path}.${key}`); } return result; }\n\n");
    out.push_str("export function parseDesktopHostResult<K extends DesktopHostOperationKind>(kind: K, value: unknown): DesktopHostResultMap[K] {\n  const item = record(value, \"$\");\n  switch (kind) {\n");
    for (name, surface) in &manifest.operations {
        let mut fields = surface.output.select.clone();
        fields.extend(surface.output.transform.iter().cloned());
        fields.sort();
        out.push_str(&format!("    case {}: {{\n", json_string(name)));
        out.push_str(&format!(
            "      exact(item, [{}], \"$\");\n",
            fields
                .iter()
                .map(|field| json_string(field))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        out.push_str("      return {\n");
        for field in &surface.output.transform {
            out.push_str(&format!(
                "        {}: projected({}, {}),\n",
                ts_property(field),
                ts_access("item", field),
                json_string(&format!("$.{field}"))
            ));
        }
        for field in &surface.output.select {
            out.push_str(&format!(
                "        {}: {},\n",
                ts_property(field),
                ts_access("item", field)
            ));
        }
        out.push_str("      } as DesktopHostResultMap[K];\n    }\n");
    }
    out.push_str("  }\n}\n\n");
    let event = &manifest.notifications["host.event"];
    let mut fields = event.output.select.clone();
    fields.extend(event.output.transform.iter().cloned());
    fields.sort();
    out.push_str("export function parseSafeHostEvent(value: unknown): SafeHostEvent { const item = record(value, \"$\");\n");
    out.push_str(&format!(
        "  exact(item, [{}], \"$\");\n  return {{\n",
        fields
            .iter()
            .map(|field| json_string(field))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    for field in &event.output.transform {
        out.push_str(&format!(
            "    {}: projected({}, {}),\n",
            ts_property(field),
            ts_access("item", field),
            json_string(&format!("$.{field}"))
        ));
    }
    for field in &event.output.select {
        out.push_str(&format!(
            "    {}: {},\n",
            ts_property(field),
            ts_access("item", field)
        ));
    }
    out.push_str("  } as SafeHostEvent;\n}\n\n");
    let operation_kinds = manifest
        .operations
        .keys()
        .map(|name| json_string(name))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!("const desktopHostOperationKinds = new Set<string>([{operation_kinds}]);\nexport function parseDesktopHostInvocation(value: unknown): DesktopHostInvocation {{ const item = record(value, \"$\"); exact(item, [\"operationId\", \"operation\"], \"$\"); if (typeof item.operationId !== \"string\" || !item.operationId.startsWith(\"desktop-op-v1-\")) throw new DesktopHostValidationError(\"$.operationId\", \"invalid logical operation ID\"); const operation = record(item.operation, \"$.operation\"); exact(operation, [\"kind\", \"input\"], \"$.operation\"); if (typeof operation.kind !== \"string\" || !desktopHostOperationKinds.has(operation.kind)) throw new DesktopHostValidationError(\"$.operation.kind\", \"unsupported operation kind\"); return {{ operationId: item.operationId as DesktopOperationId, operation: {{ kind: operation.kind, input: projected(operation.input, \"$.operation.input\") }} }} as DesktopHostInvocation; }}\nexport function parsePendingDesktopHostOperations(value: unknown): readonly DesktopHostInvocation[] {{ if (!Array.isArray(value)) throw new DesktopHostValidationError(\"$\", \"expected array\"); return value.map((item) => parseDesktopHostInvocation(item)); }}\n"));
    out.push_str("export function parseDesktopHostOperationDelivery<K extends DesktopHostOperationKind>(kind: K, value: unknown): { readonly acknowledgementToken?: DesktopHostOperationAcknowledgementToken; readonly result: DesktopHostResultMap[K] } { const item = record(value, \"$\"); exact(item, [\"acknowledgementToken\", \"result\"], \"$\"); const token = item.acknowledgementToken; if (token !== undefined && (typeof token !== \"string\" || !token.startsWith(\"desktop-operation-ack-v1-\"))) throw new DesktopHostValidationError(\"$.acknowledgementToken\", \"invalid operation acknowledgement token\"); return { ...(token === undefined ? {} : { acknowledgementToken: token as DesktopHostOperationAcknowledgementToken }), result: parseDesktopHostResult(kind, item.result) }; }\n");
    out.push_str("export function parseDesktopHostEventDelivery(value: unknown): DesktopHostEventDelivery { const item = record(value, \"$\"); exact(item, [\"acknowledgementToken\", \"event\"], \"$\"); if (typeof item.acknowledgementToken !== \"string\" || !item.acknowledgementToken.startsWith(\"desktop-event-ack-v1-\")) throw new DesktopHostValidationError(\"$.acknowledgementToken\", \"invalid acknowledgement token\"); return { acknowledgementToken: item.acknowledgementToken, event: parseSafeHostEvent(item.event) } as DesktopHostEventDelivery; }\n");
    out
}

fn render_typescript_client(manifest: &SurfaceManifest) -> String {
    let mut out =
        String::from("// @generated by `cargo run -p xtask -- generate-rpc-idl`; do not edit.\n\n");
    out.push_str("import { Channel, invoke } from \"@tauri-apps/api/core\";\nimport type { DesktopHostEventDelivery, DesktopHostInvocation, DesktopHostOperation, DesktopHostOperationAcknowledgementToken, DesktopHostOperationKind, DesktopHostResultMap, DesktopHostSubscriptionToken, DesktopOperationId, SafeHostEvent } from \"./types\";\nimport { parseDesktopHostEventDelivery, parseDesktopHostOperationDelivery, parsePendingDesktopHostOperations } from \"./validators\";\n\n");
    out.push_str(&format!(
        "export const ACKNOWLEDGE_HOST_EVENT_COMMAND = {} as const;\nexport const ACKNOWLEDGE_HOST_OPERATION_COMMAND = {} as const;\nexport const EXECUTE_HOST_OPERATION_COMMAND = {} as const;\nexport const LIST_PENDING_HOST_OPERATIONS_COMMAND = {} as const;\nexport const SUBSCRIBE_HOST_EVENTS_COMMAND = {} as const;\nexport const UNSUBSCRIBE_HOST_EVENTS_COMMAND = {} as const;\n\n",
        json_string(&manifest.commands.acknowledge),
        json_string(&manifest.commands.acknowledge_operation),
        json_string(&manifest.commands.execute),
        json_string(&manifest.commands.list_pending_operations),
        json_string(&manifest.commands.subscribe),
        json_string(&manifest.commands.unsubscribe)
    ));
    out.push_str(
        r#"export class DesktopHostExecutionError<K extends DesktopHostOperationKind = DesktopHostOperationKind> extends Error {
  constructor(readonly invocation: DesktopHostInvocation<K>, readonly cause: unknown) {
    super("Desktop host operation outcome is unresolved; retry the attached invocation");
    this.name = "DesktopHostExecutionError";
  }
}

export class DesktopHostAcknowledgementError<K extends DesktopHostOperationKind = DesktopHostOperationKind> extends Error {
  constructor(
    readonly invocation: DesktopHostInvocation<K>,
    readonly acknowledgementToken: DesktopHostOperationAcknowledgementToken,
    readonly result: DesktopHostResultMap[K] | undefined,
    readonly outcomeError: unknown,
    readonly cause: unknown,
  ) {
    super("Desktop host operation outcome is known but its acknowledgement is unresolved; retry acknowledgement, not execution");
    this.name = "DesktopHostAcknowledgementError";
  }
}

export class DesktopHostSubscriptionError extends Error {
  constructor(readonly cause: unknown, readonly closeCause?: unknown) {
    super("Desktop host subscription stopped after event delivery or acknowledgement failed");
    this.name = "DesktopHostSubscriptionError";
  }
}

export class DesktopHostClient {
  prepare<K extends DesktopHostOperationKind>(operation: Extract<DesktopHostOperation, { readonly kind: K }>): DesktopHostInvocation<K> {
    return { operationId: (`desktop-op-v1-${crypto.randomUUID()}` as DesktopOperationId), operation };
  }
  private async acknowledgeOperation(acknowledgementToken: DesktopHostOperationAcknowledgementToken): Promise<void> {
    await invoke(ACKNOWLEDGE_HOST_OPERATION_COMMAND, { acknowledgementToken });
  }
  async retryAcknowledgement<K extends DesktopHostOperationKind>(failure: DesktopHostAcknowledgementError<K>): Promise<DesktopHostResultMap[K]> {
    try {
      await this.acknowledgeOperation(failure.acknowledgementToken);
    } catch (error: unknown) {
      throw new DesktopHostAcknowledgementError(failure.invocation, failure.acknowledgementToken, failure.result, failure.outcomeError, error);
    }
    if (failure.result !== undefined) return failure.result;
    throw failure.outcomeError;
  }
  async execute<K extends DesktopHostOperationKind>(invocation: DesktopHostInvocation<K>): Promise<DesktopHostResultMap[K]> {
    let delivery: { readonly acknowledgementToken?: DesktopHostOperationAcknowledgementToken; readonly result: DesktopHostResultMap[K] };
    try {
      const value: unknown = await invoke(EXECUTE_HOST_OPERATION_COMMAND, { invocation });
      delivery = parseDesktopHostOperationDelivery(invocation.operation.kind, value);
    } catch (error: unknown) {
      const token = typeof error === "object" && error !== null && "operationAcknowledgementToken" in error ? error.operationAcknowledgementToken : undefined;
      if (typeof token === "string" && token.startsWith("desktop-operation-ack-v1-")) {
        const acknowledgementToken = token as DesktopHostOperationAcknowledgementToken;
        try {
          await this.acknowledgeOperation(acknowledgementToken);
        } catch (acknowledgementError: unknown) {
          throw new DesktopHostAcknowledgementError(invocation, acknowledgementToken, undefined, error, acknowledgementError);
        }
        throw error;
      }
      throw new DesktopHostExecutionError(invocation, error);
    }
    if (delivery.acknowledgementToken !== undefined) {
      try {
        await this.acknowledgeOperation(delivery.acknowledgementToken);
      } catch (error: unknown) {
        throw new DesktopHostAcknowledgementError(invocation, delivery.acknowledgementToken, delivery.result, undefined, error);
      }
    }
    return delivery.result;
  }
  async pendingOperations(): Promise<readonly DesktopHostInvocation[]> {
    const value: unknown = await invoke(LIST_PENDING_HOST_OPERATIONS_COMMAND);
    return parsePendingDesktopHostOperations(value);
  }
"#,
    );
    for name in manifest.operations.keys() {
        let base = pascal(name);
        out.push_str(&format!(
            "  {}(input: import(\"./types\").{}Intent): Promise<import(\"./types\").{}Result> {{ return this.execute(this.prepare({{ kind: {}, input }})); }}\n",
            camel(name), base, base, json_string(name)
        ));
    }
    out.push_str(
        r#"  async subscribe(
    scope: import("./types").DesktopHostEventScope,
    handler: (event: SafeHostEvent) => void | Promise<void>,
  ): Promise<{
    readonly token: DesktopHostSubscriptionToken;
    readonly close: () => Promise<void>;
    readonly done: Promise<void>;
  }> {
    let resolveToken!: (token: DesktopHostSubscriptionToken) => void;
    let rejectToken!: (reason: unknown) => void;
    const tokenReady = new Promise<DesktopHostSubscriptionToken>((resolve, reject) => {
      resolveToken = resolve;
      rejectToken = reject;
    });
    let tokenSettled = false;
    let readyToken: DesktopHostSubscriptionToken | undefined;
    const settleToken = (token: DesktopHostSubscriptionToken): void => {
      if (tokenSettled) return;
      tokenSettled = true;
      readyToken = token;
      resolveToken(token);
    };
    let resolveDone!: () => void;
    let rejectDone!: (reason: DesktopHostSubscriptionError) => void;
    const done = new Promise<void>((resolve, reject) => {
      resolveDone = resolve;
      rejectDone = reject;
    });
    // Subscribe setup can fail before this promise is returned. Keep that path handled while
    // preserving the original rejecting promise for callers after successful setup.
    void done.catch(() => undefined);

    let acceptingDeliveries = true;
    let deliveryChain = Promise.resolve();
    let failureRecorded = false;
    let failureCause: unknown;
    let closeCause: unknown;
    let closeFailure: DesktopHostSubscriptionError | undefined;
    let cancellationTask: Promise<void> | undefined;
    const requestClose = (): Promise<void> => {
      acceptingDeliveries = false;
      if (cancellationTask !== undefined) return cancellationTask;
      cancellationTask = (async () => {
        const token = await tokenReady;
        try {
          await invoke(UNSUBSCRIBE_HOST_EVENTS_COMMAND, { subscriptionToken: token });
        } catch (error: unknown) {
          closeCause = error;
          closeFailure = new DesktopHostSubscriptionError(error);
        }
      })();
      return cancellationTask;
    };
    let finalizationTask: Promise<void> | undefined;
    const finalize = (): Promise<void> => {
      const cancellation = requestClose();
      if (finalizationTask !== undefined) return finalizationTask;
      finalizationTask = (async () => {
        // `close()` requests backend cancellation immediately. `done` is the no-more-callbacks
        // barrier and waits for the accepted handler to return without self-waiting on reentry.
        await deliveryChain;
        await cancellation;
        let failure: DesktopHostSubscriptionError | undefined;
        if (failureRecorded) {
          failure = new DesktopHostSubscriptionError(failureCause, closeCause);
        } else {
          failure = closeFailure;
        }
        if (failure !== undefined) {
          rejectDone(failure);
          throw failure;
        }
        resolveDone();
      })();
      // Automatic failure finalization has no direct awaiter; `done` remains the public signal.
      void finalizationTask.catch(() => undefined);
      return finalizationTask;
    };

    const failSubscription = (error: unknown): void => {
      acceptingDeliveries = false;
      if (!tokenSettled) {
        tokenSettled = true;
        rejectToken(error);
        resolveDone();
        return;
      }
      if (!failureRecorded) {
        failureRecorded = true;
        failureCause = error;
      }
      void finalize();
    };

    const onReady = new Channel<unknown>((value) => {
      if (
        typeof value !== "string" ||
        !value.startsWith("desktop-host-subscription-") ||
        (readyToken !== undefined && readyToken !== value)
      ) {
        failSubscription(new Error("invalid host subscription readiness token"));
        return;
      }
      settleToken(value as DesktopHostSubscriptionToken);
    });

    const onEvent = new Channel<unknown>((value) => {
      if (!acceptingDeliveries) return;
      const deliveryTask = deliveryChain.then(async () => {
        // A queued callback that has not started is no longer accepted once close/failure begins.
        if (!acceptingDeliveries) return;
        try {
          const delivery: DesktopHostEventDelivery = parseDesktopHostEventDelivery(value);
          await handler(delivery.event);
          // A close requested from inside the handler cancels the backend delivery and returns;
          // the current callback must not write an acknowledgement after that close boundary.
          if (!acceptingDeliveries) return;
          await invoke(ACKNOWLEDGE_HOST_EVENT_COMMAND, {
            acknowledgementToken: delivery.acknowledgementToken,
          });
        } catch (error: unknown) {
          if (!failureRecorded) {
            failureRecorded = true;
            failureCause = error;
          }
          acceptingDeliveries = false;
        }
      });
      deliveryChain = deliveryTask;
      void deliveryTask.then(() => {
        if (failureRecorded) void finalize();
      });
    });

    // The readiness channel makes the cancellation handle available before the command can be
    // blocked on the first replay acknowledgement. Command completion is validated in the
    // background and becomes an observable terminal subscription failure after readiness.
    const subscriptionCommand = Promise.resolve().then(() =>
      invoke(SUBSCRIBE_HOST_EVENTS_COMMAND, { scope, onReady, onEvent }),
    );
    void subscriptionCommand.then(
      (tokenValue: unknown) => {
        if (
          typeof tokenValue !== "string" ||
          !tokenValue.startsWith("desktop-host-subscription-") ||
          readyToken === undefined ||
          tokenValue !== readyToken
        ) {
          failSubscription(new Error("host subscription readiness token does not match response token"));
        }
      },
      (error: unknown) => failSubscription(error),
    );
    const token = await tokenReady;
    return {
      token,
      close: async () => {
        const cancellation = requestClose();
        void finalize();
        await cancellation;
        if (closeFailure !== undefined) throw closeFailure;
      },
      done,
    };
  }
}
"#,
    );
    out
}

fn render_typescript_index() -> String {
    "// @generated by `cargo run -p xtask -- generate-rpc-idl`; do not edit.\n\nexport * from \"./client\";\nexport * from \"./types\";\nexport * from \"./validators\";\n"
        .to_string()
}

fn render_rust(ir: &ProtocolIr, manifest: &SurfaceManifest) -> Result<String, String> {
    let mut reachable = BTreeSet::new();
    for (name, surface) in &manifest.operations {
        let method = &ir.methods[name];
        let params = object_schema(ir, &method.params_type)?;
        for field in &surface.input.renderer_provided {
            collect_refs(
                ir,
                &params.properties[field],
                &manifest.renderer_input_variants,
                &mut reachable,
                &mut BTreeSet::new(),
            )?;
        }
    }
    let mut out = generated_rust_header(ir);
    out.push_str("use serde::{Deserialize, Serialize};\nuse serde_json::Value;\nuse starweaver_rpc_core::generated as host;\n\n");
    out.push_str("#[derive(Clone, Debug, Deserialize)]\n#[serde(deny_unknown_fields, rename_all = \"camelCase\")]\npub struct DesktopHostEventScope { pub session_id: SessionId, pub run_id: RunId }\n\n");
    out.push_str("#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]\n#[serde(transparent)]\npub struct DesktopHostEventAcknowledgementToken(pub String);\n\n#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]\n#[serde(transparent)]\npub struct DesktopHostOperationAcknowledgementToken(pub String);\n\n#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]\n#[serde(transparent)]\npub struct DesktopOperationId(pub String);\n\n#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]\n#[serde(transparent)]\npub struct DesktopPageToken(pub String);\n\n#[derive(Clone, Debug, Serialize)]\n#[serde(rename_all = \"camelCase\")]\npub struct DesktopPage { pub has_more: bool, #[serde(skip_serializing_if = \"Option::is_none\")] pub next_page_token: Option<DesktopPageToken> }\n\n");
    out.push_str("/// Backend-owned value for one supervisor-only wire field. Renderer input can never construct this type.\n#[derive(Clone, Debug, Serialize)]\n#[serde(transparent)]\npub struct SupervisorFieldValue(Value);\nimpl SupervisorFieldValue {\n    /// Converts one trusted backend-owned value into its wire representation.\n    ///\n    /// # Errors\n    ///\n    /// Returns an error when the value cannot be represented as JSON.\n    pub fn from_serializable<T: Serialize>(value: T) -> Result<Self, serde_json::Error> { serde_json::to_value(value).map(Self) }\n}\n\n");
    for name in &reachable {
        out.push_str(&render_rust_named_schema(
            ir,
            name,
            &manifest.renderer_input_variants,
        )?);
        out.push('\n');
    }
    for (name, surface) in &manifest.operations {
        let method = &ir.methods[name];
        let params = object_schema(ir, &method.params_type)?;
        let base = pascal(name);
        out.push_str("#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(deny_unknown_fields, rename_all = \"camelCase\")]\n");
        out.push_str(&format!("pub struct {base}Intent {{\n"));
        for field in &surface.input.renderer_provided {
            out.push_str(&format!(
                "    pub {}: {},\n",
                rust_field(field),
                rust_field_type(&params.properties[field], params.required.contains(field))?
            ));
        }
        if is_paginated(surface) {
            out.push_str("    pub page_token: Option<DesktopPageToken>,\n");
        }
        out.push_str("}\n\n");
        out.push_str("#[derive(Clone, Debug)]\n");
        out.push_str(&format!("pub struct {base}SupervisorFields {{\n"));
        let mut supervisor = surface.input.supervisor_constructed.clone();
        supervisor.extend(surface.input.supervisor_overridden.iter().cloned());
        supervisor.sort();
        for field in &supervisor {
            out.push_str(&format!(
                "    pub {}: SupervisorFieldValue,\n",
                rust_field(field)
            ));
        }
        out.push_str("}\n\n");
        out.push_str("#[derive(Clone, Debug, Serialize)]\n#[serde(rename_all = \"camelCase\")]\n");
        out.push_str(&format!("pub struct {base}CompleteParams {{\n"));
        for (field, kind) in &params.properties {
            if surface.input.forbidden.contains(field) {
                continue;
            }
            let field_type = if surface.input.renderer_provided.contains(field) {
                rust_field_type(kind, params.required.contains(field))?
            } else {
                "SupervisorFieldValue".to_string()
            };
            out.push_str(&format!("    pub {}: {},\n", rust_field(field), field_type));
        }
        out.push_str("}\n\n");
        out.push_str("#[derive(Clone, Debug, Serialize)]\n#[serde(rename_all = \"camelCase\")]\n");
        out.push_str(&format!("pub struct {base}Result {{\n"));
        for field in &surface.output.select {
            let result = object_schema(ir, &method.result_type)?;
            out.push_str(&format!(
                "    pub {}: {},\n",
                rust_field(field),
                rust_field_type(&result.properties[field], true)?
            ));
        }
        for field in &surface.output.transform {
            if field == "page" && is_paginated(surface) {
                out.push_str("    pub page: DesktopPage,\n");
            } else {
                out.push_str(&format!("    pub {}: Value,\n", rust_field(field)));
            }
        }
        out.push_str("}\n\n");
    }
    out.push_str("#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(tag = \"kind\", content = \"input\", deny_unknown_fields)]\npub enum DesktopHostOperation {\n");
    for name in manifest.operations.keys() {
        out.push_str(&format!(
            "    #[serde(rename = {})]\n    {}({}Intent),\n",
            json_string(name),
            pascal(name),
            pascal(name)
        ));
    }
    out.push_str("}\n\n#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(deny_unknown_fields, rename_all = \"camelCase\")]\npub struct DesktopHostInvocation { pub operation_id: DesktopOperationId, pub operation: DesktopHostOperation }\n\nimpl DesktopHostOperation {\n    #[must_use]\n    #[allow(clippy::match_same_arms)]\n    pub const fn page_token(&self) -> Option<&DesktopPageToken> { match self {\n");
    for (name, surface) in &manifest.operations {
        let base = pascal(name);
        if is_paginated(surface) {
            out.push_str(&format!(
                "        Self::{base}(intent) => intent.page_token.as_ref(),\n"
            ));
        } else {
            out.push_str(&format!("        Self::{base}(_) => None,\n"));
        }
    }
    out.push_str("    } }\n\n    #[must_use]\n    #[allow(clippy::match_same_arms)]\n    pub const fn requires_idempotency(&self) -> bool { match self {\n");
    for (name, surface) in &manifest.operations {
        let base = pascal(name);
        let requires = surface
            .input
            .supervisor_constructed
            .iter()
            .any(|field| field == "idempotencyKey");
        out.push_str(&format!("        Self::{base}(_) => {requires},\n"));
    }
    out.push_str("    } }\n}\n\n#[derive(Clone, Debug)]\npub enum SupervisorHostFields {\n");
    for name in manifest.operations.keys() {
        out.push_str(&format!(
            "    {}({}SupervisorFields),\n",
            pascal(name),
            pascal(name)
        ));
    }
    out.push_str("}\n\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct SupervisorFieldsError;\n\n/// Constructs all non-renderer host fields from fixed Desktop supervisor policy.\n///\n/// # Errors\n///\n/// Returns an error only when a fixed policy value cannot be represented as JSON.\n#[allow(clippy::too_many_lines)]\npub fn build_supervisor_fields(operation: &DesktopHostOperation, idempotency_key: &str, wire_cursor: Option<&str>) -> Result<SupervisorHostFields, SupervisorFieldsError> { match operation {\n");
    for (name, surface) in &manifest.operations {
        let base = pascal(name);
        let mut supervisor = surface.input.supervisor_constructed.clone();
        supervisor.extend(surface.input.supervisor_overridden.iter().cloned());
        supervisor.sort();
        out.push_str(&format!("    DesktopHostOperation::{base}(_) => Ok(SupervisorHostFields::{base}({base}SupervisorFields {{\n"));
        for field in &supervisor {
            let value = match field.as_str() {
                "deferredTools" | "environmentAttachments" => "Vec::<String>::new()",
                "idempotencyKey" => "idempotency_key",
                "cursor" => "wire_cursor",
                "limit" | "runLimit" => "100_u32",
                "scope" => "Option::<host::AttachmentScope>::None",
                other => {
                    return Err(format!(
                        "Desktop supervisor policy has no fixed constructor for {name}.{other}"
                    ));
                }
            };
            out.push_str(&format!(
                "        {}: SupervisorFieldValue::from_serializable({value}).map_err(|_| SupervisorFieldsError)?,\n",
                rust_field(field)
            ));
        }
        out.push_str("    })),\n");
    }
    out.push_str("} }\n\n#[derive(Clone, Debug)]\npub enum CompleteHostParams {\n");
    for name in manifest.operations.keys() {
        out.push_str(&format!(
            "    {}({}CompleteParams),\n",
            pascal(name),
            pascal(name)
        ));
    }
    out.push_str("}\n\n#[derive(Clone, Debug)]\npub struct SupervisorRequestContext { pub request_id: String, pub execution_domain: String }\n#[derive(Clone, Debug)]\npub struct CompleteHostRequest { pub execution_domain: String, pub request: host::HostRequest }\n\n");
    out.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum BuildHostRequestError { AuthorityMismatch, InvalidGeneratedRequest }\n\n/// Builds an exact generated host call from disjoint renderer and supervisor authority.\n///\n/// # Errors\n///\n/// Returns an error when authority variants mismatch or the completed generated params violate the canonical host schema.\n#[allow(clippy::too_many_lines)]\npub fn build_complete_host_request(operation: DesktopHostOperation, supervisor: SupervisorHostFields, context: SupervisorRequestContext) -> Result<CompleteHostRequest, BuildHostRequestError> {\n    let params = match (operation, supervisor) {\n");
    for (name, surface) in &manifest.operations {
        let base = pascal(name);
        let method = &ir.methods[name];
        let params = object_schema(ir, &method.params_type)?;
        let intent_binding = if surface.input.renderer_provided.is_empty() {
            "_intent"
        } else {
            "intent"
        };
        let supervisor_binding = if surface.input.supervisor_constructed.is_empty()
            && surface.input.supervisor_overridden.is_empty()
        {
            "_supervisor"
        } else {
            "supervisor"
        };
        out.push_str(&format!("        (DesktopHostOperation::{base}({intent_binding}), SupervisorHostFields::{base}({supervisor_binding})) => CompleteHostParams::{base}({base}CompleteParams {{\n"));
        for field in params.properties.keys() {
            if surface.input.forbidden.contains(field) {
                continue;
            }
            let source = if surface.input.renderer_provided.contains(field) {
                "intent"
            } else {
                "supervisor"
            };
            out.push_str(&format!(
                "            {}: {}.{},\n",
                rust_field(field),
                source,
                rust_field(field)
            ));
        }
        out.push_str("        }),\n");
    }
    out.push_str("        _ => return Err(BuildHostRequestError::AuthorityMismatch),\n    };\n    let (method, params) = match &params {\n");
    for name in manifest.operations.keys() {
        let base = pascal(name);
        out.push_str(&format!(
            "        CompleteHostParams::{base}(params) => ({}, serde_json::to_value(params)),\n",
            json_string(name)
        ));
    }
    out.push_str("    };\n    let params = params.map_err(|_| BuildHostRequestError::InvalidGeneratedRequest)?;\n    let frame = serde_json::to_vec(&serde_json::json!({\"jsonrpc\":\"2.0\",\"id\":context.request_id,\"method\":method,\"params\":params})).map_err(|_| BuildHostRequestError::InvalidGeneratedRequest)?;\n    let request = host::decode_request_frame(&frame).map_err(|_| BuildHostRequestError::InvalidGeneratedRequest)?;\n    Ok(CompleteHostRequest { execution_domain: context.execution_domain, request })\n}\n\n");
    out.push_str(
        "#[derive(Clone, Debug, Serialize)]\n#[serde(untagged)]\npub enum DesktopHostResult {\n",
    );
    for name in manifest.operations.keys() {
        let base = pascal(name);
        out.push_str(&format!("    {base}({base}Result),\n"));
    }
    out.push_str("}\n\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum ProjectionError { UnsupportedOperation, InvalidGeneratedValue, UnauthorizedEventClass }\n\n/// Projects one typed host result into the reviewed renderer-safe result sum.\n///\n/// # Errors\n///\n/// Returns an error for operations outside the renderer manifest or invalid generated values.\n#[allow(clippy::too_many_lines)]\npub fn project_host_result(result: host::HostResult, next_page_token: Option<DesktopPageToken>) -> Result<DesktopHostResult, ProjectionError> { match result {\n");
    for (name, surface) in &manifest.operations {
        let base = pascal(name);
        out.push_str(&format!("    host::HostResult::{base}(value) => {{ let value = serde_json::to_value(value).map_err(|_| ProjectionError::InvalidGeneratedValue)?; let object = value.as_object().ok_or(ProjectionError::InvalidGeneratedValue)?; Ok(DesktopHostResult::{base}({base}Result {{\n"));
        for field in &surface.output.transform {
            if field == "page" && is_paginated(surface) {
                out.push_str("        page: project_page(object, next_page_token)?,\n");
            } else {
                out.push_str(&format!(
                    "        {}: project_field(object, {})?,\n",
                    rust_field(field),
                    json_string(field)
                ));
            }
        }
        for field in &surface.output.select {
            out.push_str(&format!(
                "        {}: serde_json::from_value(object.get({}).cloned().ok_or(ProjectionError::InvalidGeneratedValue)?).map_err(|_| ProjectionError::InvalidGeneratedValue)?,\n",
                rust_field(field),
                json_string(field)
            ));
        }
        out.push_str("    })) },\n");
    }
    out.push_str("    _ => Err(ProjectionError::UnsupportedOperation),\n} }\n\n#[derive(Clone, Debug, Serialize)]\n#[serde(rename_all = \"camelCase\")]\npub struct DesktopHostOperationDelivery { #[serde(skip_serializing_if = \"Option::is_none\")] pub acknowledgement_token: Option<DesktopHostOperationAcknowledgementToken>, pub result: DesktopHostResult }\n\nfn project_page(object: &serde_json::Map<String, Value>, next_page_token: Option<DesktopPageToken>) -> Result<DesktopPage, ProjectionError> { let page = object.get(\"page\").and_then(Value::as_object).ok_or(ProjectionError::InvalidGeneratedValue)?; let has_more = page.get(\"hasMore\").and_then(Value::as_bool).ok_or(ProjectionError::InvalidGeneratedValue)?; if has_more != next_page_token.is_some() { return Err(ProjectionError::InvalidGeneratedValue); } Ok(DesktopPage { has_more, next_page_token }) }\nfn project_field(object: &serde_json::Map<String, Value>, field: &str) -> Result<Value, ProjectionError> { object.get(field).cloned().map(project_value).ok_or(ProjectionError::InvalidGeneratedValue) }\nfn project_value(value: Value) -> Value { match value { Value::Array(values) => Value::Array(values.into_iter().map(project_value).collect()), Value::Object(values) => Value::Object(values.into_iter().filter(|(key, _)| !is_forbidden_projection_key(key)).map(|(key, value)| (key, project_value(value))).collect()), value => value } }\nfn is_forbidden_projection_key(key: &str) -> bool { matches!(key, \"acceptedCursor\" | \"cursor\" | \"deliverySequence\" | \"diagnosticRef\" | \"fenceCursor\" | \"fingerprint\" | \"idempotencyKey\" | \"nextCursor\" | \"nextDeliverySequence\" | \"scope\" | \"subscriptionId\") }\n\n");
    let notification = &manifest.notifications["host.event"];
    out.push_str("#[derive(Clone, Debug, Serialize)]\n#[serde(rename_all = \"camelCase\")]\n");
    out.push_str(&format!("pub struct {} {{\n", notification.projection));
    for field in &notification.output.transform {
        out.push_str(&format!("    pub {}: Value,\n", rust_field(field)));
    }
    out.push_str("}\n\n#[derive(Clone, Debug, Serialize)]\n#[serde(rename_all = \"camelCase\")]\npub struct DesktopHostEventDelivery { pub acknowledgement_token: DesktopHostEventAcknowledgementToken, pub event: SafeHostEvent }\n\n/// Projects an admitted conversation notification without transport-owned subscription or cursor fields.\n///\n/// # Errors\n///\n/// Returns an error for internal notifications or event classes outside the reviewed Desktop profile.\npub fn project_host_notification(notification: host::HostNotification) -> Result<");
    out.push_str(&notification.projection);
    out.push_str(", ProjectionError> { let host::HostNotificationParams::HostEvent(params) = notification.params else { return Err(ProjectionError::UnsupportedOperation); }; if !matches!(&params.delivery.record.event, ");
    let allowed_patterns = DESKTOP_EVENT_KINDS
        .iter()
        .filter_map(|event_kind| ir.event_classes.get(*event_kind))
        .map(|class| format!("host::HostEvent::{}(_)", pascal(&class.schema_type)))
        .collect::<Vec<_>>()
        .join(" | ");
    out.push_str(&allowed_patterns);
    out.push_str(") { return Err(ProjectionError::UnauthorizedEventClass); } let value = serde_json::to_value(params).map_err(|_| ProjectionError::InvalidGeneratedValue)?; let object = value.as_object().ok_or(ProjectionError::InvalidGeneratedValue)?; Ok(");
    out.push_str(&notification.projection);
    out.push_str(" { ");
    for field in &notification.output.transform {
        out.push_str(&format!(
            "{}: project_field(object, {})?, ",
            rust_field(field),
            json_string(field)
        ));
    }
    out.push_str("}) }\n");
    Ok(out)
}

fn collect_refs(
    ir: &ProtocolIr,
    kind: &SchemaKind,
    renderer_input_variants: &BTreeMap<String, Vec<String>>,
    output: &mut BTreeSet<String>,
    visiting: &mut BTreeSet<String>,
) -> Result<(), String> {
    match kind {
        SchemaKind::Ref(name) => {
            if !output.insert(name.clone()) {
                return Ok(());
            }
            if !visiting.insert(name.clone()) {
                return Err(format!("recursive renderer Rust schema {name}"));
            }
            let schema = &ir.schemas[name].kind;
            if let Some(allowed) = renderer_input_variants.get(name) {
                let SchemaKind::OneOf { variants, .. } = schema else {
                    return Err(format!(
                        "renderer input variant target {name} is not a union"
                    ));
                };
                for variant in variants.iter().filter(|variant| {
                    matches!(variant, SchemaKind::Ref(target) if allowed.contains(target))
                }) {
                    collect_refs(
                        ir,
                        variant,
                        renderer_input_variants,
                        output,
                        visiting,
                    )?;
                }
            } else {
                collect_refs(ir, schema, renderer_input_variants, output, visiting)?;
            }
            visiting.remove(name);
        }
        SchemaKind::Object(object) => {
            for kind in object.properties.values() {
                collect_refs(ir, kind, renderer_input_variants, output, visiting)?;
            }
        }
        SchemaKind::Array { items, .. } => {
            collect_refs(ir, items, renderer_input_variants, output, visiting)?;
        }
        SchemaKind::OneOf { variants, .. } => {
            for variant in variants {
                collect_refs(ir, variant, renderer_input_variants, output, visiting)?;
            }
        }
        SchemaKind::JsonObject
        | SchemaKind::String(_)
        | SchemaKind::Integer { .. }
        | SchemaKind::Boolean
        | SchemaKind::Null => {}
    }
    Ok(())
}

fn render_rust_named_schema(
    ir: &ProtocolIr,
    name: &str,
    renderer_input_variants: &BTreeMap<String, Vec<String>>,
) -> Result<String, String> {
    let kind = &ir.schemas[name].kind;
    Ok(match kind {
        SchemaKind::String(value) if !value.enum_values.is_empty() => {
            let mut out =
                String::from("#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]\n");
            out.push_str(&format!("pub enum {} {{\n", rust_type_name(name)));
            for item in &value.enum_values {
                out.push_str(&format!(
                    "    #[serde(rename = {})]\n    {},\n",
                    json_string(item),
                    pascal(item)
                ));
            }
            out.push_str("}\n");
            out
        }
        SchemaKind::String(value) if value.const_value.is_some() => {
            let item = value.const_value.as_deref().unwrap_or_default();
            format!(
                "#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]\npub enum {} {{ #[serde(rename = {})] Value }}\n",
                rust_type_name(name),
                json_string(item)
            )
        }
        SchemaKind::String(_) => format!(
            "#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]\n#[serde(transparent)]\npub struct {}(pub String);\n",
            rust_type_name(name)
        ),
        SchemaKind::Integer { .. } => format!("pub type {} = i64;\n", rust_type_name(name)),
        SchemaKind::Boolean => format!("pub type {} = bool;\n", rust_type_name(name)),
        SchemaKind::Null => format!("pub type {} = ();\n", rust_type_name(name)),
        SchemaKind::Array { items, .. } => format!(
            "pub type {} = Vec<{}>;\n",
            rust_type_name(name),
            rust_kind_type(items)?
        ),
        SchemaKind::Object(object) => render_rust_object(name, object)?,
        SchemaKind::JsonObject => {
            return Err(format!(
                "arbitrary JSON schema {name} cannot cross the Desktop renderer boundary"
            ));
        }
        SchemaKind::OneOf {
            variants,
            discriminator,
            ..
        } => {
            let projected_variants = renderer_input_variants.get(name).map_or_else(
                || variants.clone(),
                |allowed| {
                    variants
                        .iter()
                        .filter(|variant| {
                            matches!(variant, SchemaKind::Ref(target) if allowed.contains(target))
                        })
                        .cloned()
                        .collect::<Vec<_>>()
                },
            );
            render_rust_union(ir, name, &projected_variants, discriminator.as_deref())?
        }
        SchemaKind::Ref(target) => format!(
            "pub type {} = {};\n",
            rust_type_name(name),
            rust_type_name(target)
        ),
    })
}

fn render_rust_object(name: &str, object: &ObjectSchema) -> Result<String, String> {
    let mut out = String::from(
        "#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(deny_unknown_fields, rename_all = \"camelCase\")]\n",
    );
    out.push_str(&format!("pub struct {} {{\n", rust_type_name(name)));
    for (field, kind) in &object.properties {
        out.push_str(&format!(
            "    pub {}: {},\n",
            rust_field(field),
            rust_field_type(kind, object.required.contains(field))?
        ));
    }
    out.push_str("}\n");
    Ok(out)
}

fn render_rust_union(
    ir: &ProtocolIr,
    name: &str,
    variants: &[SchemaKind],
    discriminator: Option<&str>,
) -> Result<String, String> {
    let non_null = variants
        .iter()
        .filter(|variant| !matches!(variant, SchemaKind::Null))
        .collect::<Vec<_>>();
    if non_null.len() == 1 && non_null.len() != variants.len() {
        return Ok(format!(
            "pub type {} = Option<{}>;\n",
            rust_type_name(name),
            rust_kind_type(non_null[0])?
        ));
    }
    let mut out = String::from("#[derive(Clone, Debug, Deserialize, Serialize)]\n");
    if let Some(tag) = discriminator {
        out.push_str(&format!("#[serde(tag = {})]\n", json_string(tag)));
    } else {
        out.push_str("#[serde(untagged)]\n");
    }
    out.push_str(&format!("pub enum {} {{\n", rust_type_name(name)));
    for (index, variant) in non_null.iter().enumerate() {
        if let (Some(tag), SchemaKind::Ref(target)) = (discriminator, *variant) {
            let object = object_schema(ir, target)?;
            let tag_value = object
                .properties
                .get(tag)
                .and_then(|kind| match kind {
                    SchemaKind::String(value) => value.const_value.as_deref(),
                    _ => None,
                })
                .ok_or_else(|| format!("union {name} variant {target} has no const tag {tag}"))?;
            out.push_str(&format!(
                "    #[serde(rename = {})]\n    {} {{\n",
                json_string(tag_value),
                pascal(tag_value)
            ));
            for (field, kind) in &object.properties {
                if field == tag {
                    continue;
                }
                out.push_str(&format!(
                    "        {}: {},\n",
                    rust_field(field),
                    rust_field_type(kind, object.required.contains(field))?
                ));
            }
            out.push_str("    },\n");
        } else {
            out.push_str(&format!(
                "    V{}({}),\n",
                index + 1,
                rust_kind_type(variant)?
            ));
        }
    }
    out.push_str("}\n");
    Ok(out)
}

fn rust_field_type(kind: &SchemaKind, required: bool) -> Result<String, String> {
    let (base, nullable) = match kind {
        SchemaKind::OneOf { variants, .. }
            if variants
                .iter()
                .any(|variant| matches!(variant, SchemaKind::Null)) =>
        {
            let non_null = variants
                .iter()
                .filter(|variant| !matches!(variant, SchemaKind::Null))
                .collect::<Vec<_>>();
            if non_null.len() != 1 {
                return Err(
                    "nullable renderer union must contain exactly one non-null variant".to_string(),
                );
            }
            (rust_kind_type(non_null[0])?, true)
        }
        _ => (rust_kind_type(kind)?, false),
    };
    if !required || nullable {
        Ok(format!("Option<{base}>"))
    } else {
        Ok(base)
    }
}

fn rust_kind_type(kind: &SchemaKind) -> Result<String, String> {
    Ok(match kind {
        SchemaKind::Ref(name) => rust_type_name(name),
        SchemaKind::String(_) => "String".to_string(),
        SchemaKind::Integer { .. } => "i64".to_string(),
        SchemaKind::Boolean => "bool".to_string(),
        SchemaKind::Null => "()".to_string(),
        SchemaKind::JsonObject => {
            return Err("arbitrary JSON cannot cross the Desktop renderer boundary".to_string());
        }
        SchemaKind::Array { items, .. } => format!("Vec<{}>", rust_kind_type(items)?),
        SchemaKind::OneOf { variants, .. } => {
            let non_null = variants
                .iter()
                .filter(|variant| !matches!(variant, SchemaKind::Null))
                .collect::<Vec<_>>();
            if non_null.len() != 1 {
                return Err("anonymous Rust union requires one non-null variant".to_string());
            }
            format!("Option<{}>", rust_kind_type(non_null[0])?)
        }
        SchemaKind::Object(_) => {
            return Err("anonymous object cannot cross the Desktop renderer boundary".to_string());
        }
    })
}

fn rustfmt_source(source: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| format!("start rustfmt for generated Desktop bindings: {error}"))?;
    child
        .stdin
        .take()
        .ok_or("rustfmt stdin unavailable")?
        .write_all(source.as_bytes())
        .map_err(|error| error.to_string())?;
    let output = child
        .wait_with_output()
        .map_err(|error| error.to_string())?;
    if !output.status.success() {
        return Err(format!(
            "generated Desktop Rust failed rustfmt: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout).map_err(|error| error.to_string())
}

fn render_permission(command: &str, description: &str) -> String {
    let identifier = permission_identifier(command);
    format!(
        "# @generated by `cargo run -p xtask -- generate-rpc-idl`; do not edit.\n[[permission]]\nidentifier = \"{identifier}\"\ndescription = \"{description}\"\ncommands.allow = [\"{command}\"]\n"
    )
}

fn permission_identifier(command: &str) -> String {
    format!("allow-{}", command.replace('_', "-"))
}

fn render_capability_fragment(
    ir: &ProtocolIr,
    manifest: &SurfaceManifest,
) -> Result<String, String> {
    let value = serde_json::json!({
        "$schema": "../gen/schemas/desktop-schema.json",
        "description": format!(
            "Generated least-authority host operation fragment for {}",
            ir.identity.schema_digest
        ),
        "identifier": "generated-host",
        "permissions": [
            permission_identifier(&manifest.commands.acknowledge),
            permission_identifier(&manifest.commands.acknowledge_operation),
            permission_identifier(&manifest.commands.execute),
            permission_identifier(&manifest.commands.list_pending_operations),
            permission_identifier(&manifest.commands.subscribe),
            permission_identifier(&manifest.commands.unsubscribe),
        ],
        "windows": ["main"],
    });
    Ok(format!(
        "{}\n",
        serde_json::to_string_pretty(&value).map_err(|error| error.to_string())?
    ))
}

fn generated_ts_comment(ir: &ProtocolIr) -> String {
    format!(
        "// @generated by `cargo run -p xtask -- generate-rpc-idl`; do not edit.\n// Protocol digest: {}\n\n",
        ir.identity.schema_digest
    )
}

fn generated_ts_header(ir: &ProtocolIr) -> String {
    format!(
        "{}export const DESKTOP_HOST_PROTOCOL_DIGEST = {} as const;\n\n",
        generated_ts_comment(ir),
        json_string(&ir.identity.schema_digest)
    )
}

fn generated_rust_header(ir: &ProtocolIr) -> String {
    format!(
        "//! Generated renderer-safe Desktop host bindings. Do not edit.\n#![allow(missing_docs)]\n\npub const DESKTOP_HOST_PROTOCOL_DIGEST: &str = {};\n\n",
        json_string(&ir.identity.schema_digest)
    )
}

fn insert(files: &mut BTreeMap<PathBuf, Vec<u8>>, path: &str, source: String) {
    let mut normalized = source.replace("\r\n", "\n").replace('\r', "\n");
    if !normalized.ends_with('\n') {
        normalized.push('\n');
    }
    files.insert(PathBuf::from(path), normalized.into_bytes());
}

fn is_paginated(surface: &SurfaceOperation) -> bool {
    surface
        .input
        .supervisor_overridden
        .iter()
        .any(|field| field == "cursor")
        && surface.output.transform.iter().any(|field| field == "page")
}

fn pascal(value: &str) -> String {
    let mut output = String::new();
    let mut uppercase = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase {
                output.push(character.to_ascii_uppercase());
                uppercase = false;
            } else {
                output.push(character);
            }
        } else {
            uppercase = true;
        }
    }
    output
}

fn camel(value: &str) -> String {
    let pascal = pascal(value);
    let mut characters = pascal.chars();
    characters
        .next()
        .map(|first| first.to_ascii_lowercase().to_string() + characters.as_str())
        .unwrap_or_default()
}

fn rust_type_name(value: &str) -> String {
    pascal(value)
}

fn rust_field(value: &str) -> String {
    let mut output = String::new();
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_uppercase() && index > 0 {
            output.push('_');
        }
        if character.is_ascii_alphanumeric() {
            output.push(character.to_ascii_lowercase());
        } else if !output.ends_with('_') {
            output.push('_');
        }
    }
    match output.as_str() {
        "type" | "match" | "ref" | "self" | "crate" | "mod" | "move" => {
            format!("r#{output}")
        }
        _ => output,
    }
}

fn ts_property(value: &str) -> String {
    if is_ts_identifier(value) {
        value.to_string()
    } else {
        json_string(value)
    }
}

fn ts_access(base: &str, field: &str) -> String {
    if is_ts_identifier(field) {
        format!("{base}.{field}")
    } else {
        format!("{base}[{}]", json_string(field))
    }
}

fn is_ts_identifier(value: &str) -> bool {
    value.chars().enumerate().all(|(index, character)| {
        character == '_'
            || character == '$'
            || (character.is_ascii_alphanumeric() && (index > 0 || !character.is_ascii_digit()))
    })
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"\"".to_string())
}
