//! Build script for preparing embeddable Starweaver Claw web console assets.

use std::{env, error::Error, fs, io, path::Path};

const WEB_DIST_DIR: &str = "web/dist";
const OUT_WEB_DIST_DIR: &str = "claw-web-dist";

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed={WEB_DIST_DIR}");
    println!("cargo:rerun-if-changed=web/package.json");
    println!("cargo:rerun-if-changed=web/pnpm-lock.yaml");

    let manifest_dir = env::var_os("CARGO_MANIFEST_DIR").ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::NotFound,
            "CARGO_MANIFEST_DIR is set by Cargo",
        )
    })?;
    let out_dir = env::var_os("OUT_DIR")
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "OUT_DIR is set by Cargo"))?;
    let source = Path::new(&manifest_dir).join(WEB_DIST_DIR);
    let target = Path::new(&out_dir).join(OUT_WEB_DIST_DIR);

    if target.exists() {
        fs::remove_dir_all(&target)?;
    }
    fs::create_dir_all(&target)?;

    if source.join("index.html").is_file() {
        copy_dir(&source, &target)?;
    } else {
        write_placeholder_bundle(&target)?;
    }

    Ok(())
}

fn copy_dir(source: &Path, target: &Path) -> io::Result<()> {
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let target_path = target.join(entry.file_name());
        if source_path.is_dir() {
            fs::create_dir_all(&target_path)?;
            copy_dir(&source_path, &target_path)?;
        } else {
            fs::copy(&source_path, &target_path)?;
        }
    }
    Ok(())
}

fn write_placeholder_bundle(target: &Path) -> io::Result<()> {
    fs::write(
        target.join("index.html"),
        r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Starweaver Claw</title>
  </head>
  <body>
    <main id="root">
      <h1>Starweaver Claw</h1>
      <p>The web console bundle is generated by running <code>make claw-web-check</code>.</p>
    </main>
  </body>
</html>
"#,
    )?;
    Ok(())
}
