"""Python bindings for Starweaver."""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _distribution_version

from ._native import version
from .agent import (
    Agent,
    AgentRun,
    AgentRuntime,
    AgentSession,
    AgentStream,
    ApprovalDecision,
    BusMessage,
    ControlReceipt,
    DeferredResult,
    HitlSnapshot,
    MessageBus,
    MessageDelivery,
    PendingApproval,
    PendingDeferred,
    RunResult,
    RunStatusSnapshot,
    SessionArchive,
    StreamEvent,
    StreamRunResult,
    create_agent,
    create_agent_runtime,
)
from .capability import CapabilityBundle
from .environment import (
    EnvdEnvironment,
    Environment,
    EnvironmentProvider,
    FileOperator,
    LocalEnvironment,
    PythonEnvironmentProvider,
    Shell,
    ShellProcess,
    VirtualEnvironment,
    VirtualMount,
    VirtualPath,
    WorkspaceBinding,
)
from .errors import (
    AgentError,
    ApprovalRequired,
    CallDeferred,
    Cancelled,
    InvalidArguments,
    ModelError,
    ModelRetry,
    OutputError,
    OutputRetry,
    OutputValidationFailed,
    StarweaverError,
    StateError,
    StreamError,
    Timeout,
    ToolError,
)
from .media import MediaUploader, MediaUploadRequest
from .model import ModelSettings, ProviderAuth, ProviderModel, RequestParams
from .observability import (
    PricingEstimate,
    TraceMetadata,
    Usage,
    UsageAgentTotal,
    UsageSnapshot,
    UsageSnapshotEntry,
)
from .output import (
    OutputContext,
    OutputFunction,
    OutputPolicy,
    OutputSchema,
    OutputValidator,
    OutputValue,
    output_validator,
)
from .resources import (
    RESOURCE_REF_KIND_KEY,
    BaseResource,
    InstructableResource,
    ResourceRef,
    ResourceRegistry,
    ResourceRegistryState,
    ResumableResource,
)
from .runtime import RuntimeConfig
from .skills import SkillPackage, SkillRegistry, SkillSourceScope
from .store import (
    ApprovalRecord,
    CheckpointRef,
    DeferredToolRecord,
    ExecutionStatus,
    InMemorySessionStore,
    InputPart,
    JsonSessionStore,
    RunRecord,
    RunStatus,
    SessionRecord,
    SessionResumeSnapshot,
    SessionStatus,
    SessionStore,
    SqliteReplayEventLog,
    SqliteSessionStore,
    SqliteStreamArchive,
    StreamRecord,
)
from .stream_adapter import StreamAdapter
from .subagent import Subagent
from .testing import FunctionModel, TestModel
from .tool import BaseTool, Tool, ToolContext, ToolResult, tool
from .toolset import (
    AbstractToolset,
    FunctionToolset,
    McpPromptSpec,
    McpResourceSpec,
    McpSamplingSpec,
    McpSubscriptionSpec,
    McpToolset,
    McpToolSpec,
    McpTransport,
    PythonDynamicToolset,
    ToolLibrary,
    ToolProxyToolset,
    ToolSearchToolset,
    Toolset,
    ToolsetContext,
    ToolsetFactory,
    ToolsetIdentity,
    ToolsetIdIssue,
    ToolsetIdValidation,
    ToolsetLifecyclePolicy,
    ToolsetLifecycleReport,
    ToolsetLifecycleState,
    ToolsetPreparation,
    environment_toolsets,
    filesystem_toolset,
    shell_toolset,
    toolset_factory,
    validate_toolset_ids,
    validate_toolsets_for_durability,
)

try:
    __version__ = _distribution_version("starweaver")
except PackageNotFoundError:
    __version__ = version()

__all__ = [
    "RESOURCE_REF_KIND_KEY",
    "AbstractToolset",
    "Agent",
    "AgentError",
    "AgentRun",
    "AgentRuntime",
    "AgentSession",
    "AgentStream",
    "ApprovalDecision",
    "ApprovalRecord",
    "ApprovalRequired",
    "BaseResource",
    "BaseTool",
    "BusMessage",
    "CallDeferred",
    "Cancelled",
    "CapabilityBundle",
    "CheckpointRef",
    "ControlReceipt",
    "DeferredResult",
    "DeferredToolRecord",
    "EnvdEnvironment",
    "Environment",
    "EnvironmentProvider",
    "ExecutionStatus",
    "FileOperator",
    "FunctionModel",
    "FunctionToolset",
    "HitlSnapshot",
    "InMemorySessionStore",
    "InputPart",
    "InstructableResource",
    "InvalidArguments",
    "JsonSessionStore",
    "LocalEnvironment",
    "McpPromptSpec",
    "McpResourceSpec",
    "McpSamplingSpec",
    "McpSubscriptionSpec",
    "McpToolSpec",
    "McpToolset",
    "McpTransport",
    "MediaUploadRequest",
    "MediaUploader",
    "MessageBus",
    "MessageDelivery",
    "ModelError",
    "ModelRetry",
    "ModelSettings",
    "OutputContext",
    "OutputError",
    "OutputFunction",
    "OutputPolicy",
    "OutputRetry",
    "OutputSchema",
    "OutputValidationFailed",
    "OutputValidator",
    "OutputValue",
    "PendingApproval",
    "PendingDeferred",
    "PricingEstimate",
    "ProviderAuth",
    "ProviderModel",
    "PythonDynamicToolset",
    "PythonEnvironmentProvider",
    "RequestParams",
    "ResourceRef",
    "ResourceRegistry",
    "ResourceRegistryState",
    "ResumableResource",
    "RunRecord",
    "RunResult",
    "RunStatus",
    "RunStatusSnapshot",
    "RuntimeConfig",
    "SessionArchive",
    "SessionRecord",
    "SessionResumeSnapshot",
    "SessionStatus",
    "SessionStore",
    "Shell",
    "ShellProcess",
    "SkillPackage",
    "SkillRegistry",
    "SkillSourceScope",
    "SqliteReplayEventLog",
    "SqliteSessionStore",
    "SqliteStreamArchive",
    "StarweaverError",
    "StateError",
    "StreamAdapter",
    "StreamError",
    "StreamEvent",
    "StreamRecord",
    "StreamRunResult",
    "Subagent",
    "TestModel",
    "Timeout",
    "Tool",
    "ToolContext",
    "ToolError",
    "ToolLibrary",
    "ToolProxyToolset",
    "ToolResult",
    "ToolSearchToolset",
    "Toolset",
    "ToolsetContext",
    "ToolsetFactory",
    "ToolsetIdIssue",
    "ToolsetIdValidation",
    "ToolsetIdentity",
    "ToolsetLifecyclePolicy",
    "ToolsetLifecycleReport",
    "ToolsetLifecycleState",
    "ToolsetPreparation",
    "TraceMetadata",
    "Usage",
    "UsageAgentTotal",
    "UsageSnapshot",
    "UsageSnapshotEntry",
    "VirtualEnvironment",
    "VirtualMount",
    "VirtualPath",
    "WorkspaceBinding",
    "__version__",
    "create_agent",
    "create_agent_runtime",
    "environment_toolsets",
    "filesystem_toolset",
    "output_validator",
    "shell_toolset",
    "tool",
    "toolset_factory",
    "validate_toolset_ids",
    "validate_toolsets_for_durability",
    "version",
]
