from collections.abc import Awaitable
from typing import Any

__version__: str

def version() -> str: ...
def sleep_echo(value: object, delay_ms: int = 0) -> Awaitable[Any]: ...
def oauth_provider_status(
    provider_name: str,
    auth_file: str | None = None,
) -> dict[str, object]: ...
def oauth_provider_redacted_record(
    provider_name: str,
    auth_file: str | None = None,
) -> dict[str, object] | None: ...

class TestModel:
    def __init__(self, text: str | None = None, responses: object | None = None) -> None: ...
    @staticmethod
    def text(text: str) -> TestModel: ...
    @staticmethod
    def responses(responses: object) -> TestModel: ...
    @staticmethod
    def tool_call_response(calls: object) -> object: ...
    def captured_messages(self) -> list[object]: ...
    def captured_params(self) -> list[object]: ...

class FunctionModel:
    def __init__(
        self,
        callback: object,
        event_loop: object,
        model_name: str | None = None,
    ) -> None: ...
    def captured_messages(self) -> list[object]: ...
    def captured_params(self) -> list[object]: ...

class ModelSettings:
    def __init__(self, value: object | None = None, **kwargs: object) -> None: ...
    @staticmethod
    def preset(name: str) -> ModelSettings: ...
    def to_dict(self) -> dict[str, object]: ...

class RequestParams:
    def __init__(self, value: object | None = None, **kwargs: object) -> None: ...
    def to_dict(self) -> dict[str, object]: ...

class ProviderModel:
    @staticmethod
    def from_model_id(
        model_id: str,
        api_key: str | None = None,
        api_key_env: str | None = None,
        model_config_preset: str | None = None,
        model_settings: object | None = None,
        base_url: str | None = None,
        endpoint_path: str | None = None,
    ) -> ProviderModel: ...
    @staticmethod
    def codex_oauth(
        model_name: str,
        model_settings: object | None = None,
        auth_file: str | None = None,
    ) -> ProviderModel: ...
    @staticmethod
    def openai_responses(
        model_name: str,
        api_key: str | None = None,
        api_key_env: str | None = None,
        model_config_preset: str | None = None,
        model_settings: object | None = None,
        base_url: str | None = None,
        endpoint_path: str | None = None,
    ) -> ProviderModel: ...
    @staticmethod
    def openai_chat(
        model_name: str,
        api_key: str | None = None,
        api_key_env: str | None = None,
        model_config_preset: str | None = None,
        model_settings: object | None = None,
        base_url: str | None = None,
        endpoint_path: str | None = None,
    ) -> ProviderModel: ...
    @staticmethod
    def anthropic(
        model_name: str,
        api_key: str | None = None,
        api_key_env: str | None = None,
        model_config_preset: str | None = None,
        model_settings: object | None = None,
        base_url: str | None = None,
        endpoint_path: str | None = None,
    ) -> ProviderModel: ...
    @staticmethod
    def gemini(
        model_name: str,
        api_key: str | None = None,
        api_key_env: str | None = None,
        model_config_preset: str | None = None,
        model_settings: object | None = None,
        base_url: str | None = None,
        endpoint_path: str | None = None,
    ) -> ProviderModel: ...

class OutputSchema:
    def __init__(
        self,
        name: str,
        schema: object,
        description: str | None = None,
        strict: bool = True,
    ) -> None: ...
    def request_schema(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...

class OutputContext:
    @property
    def run_id(self) -> str: ...
    @property
    def conversation_id(self) -> str: ...
    @property
    def run_step(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def metadata(self) -> dict[str, object]: ...
    def raw_state(self) -> dict[str, object]: ...

class OutputValue:
    @staticmethod
    def text(value: str) -> OutputValue: ...
    @staticmethod
    def json(value: object) -> OutputValue: ...
    def to_python(self) -> object: ...

class OutputValidator:
    def __init__(self, callback: object, event_loop: object) -> None: ...

class OutputFunction:
    def __init__(
        self,
        name: str,
        parameters_schema: object,
        callback: object,
        event_loop: object,
        description: str | None = None,
    ) -> None: ...
    def definition_json(self) -> dict[str, object]: ...

class OutputPolicy:
    def __init__(self) -> None: ...
    @staticmethod
    def text() -> OutputPolicy: ...
    @staticmethod
    def structured(schema: object) -> OutputPolicy: ...
    @staticmethod
    def auto(schema: object) -> OutputPolicy: ...
    @staticmethod
    def native_json_schema(schema: object) -> OutputPolicy: ...
    @staticmethod
    def native_json_object(schema: object) -> OutputPolicy: ...
    @staticmethod
    def tool(schema: object) -> OutputPolicy: ...
    @staticmethod
    def tool_or_text(schema: object) -> OutputPolicy: ...
    @staticmethod
    def prompted(schema: object) -> OutputPolicy: ...
    @staticmethod
    def image() -> OutputPolicy: ...
    def with_retries(self, retries: int) -> OutputPolicy: ...
    def with_mode(self, mode: str) -> OutputPolicy: ...
    def allow_text_output(self, allow: bool) -> OutputPolicy: ...
    def allow_image_output(self, allow: bool) -> OutputPolicy: ...
    def with_validator(self, validator: OutputValidator) -> OutputPolicy: ...
    def with_function(self, function: OutputFunction) -> OutputPolicy: ...

class CapabilityBundle:
    def __init__(
        self,
        name: str,
        instructions: list[str] | None = None,
        tools: list[PythonTool] | None = None,
        model_settings: object | None = None,
        request_params: object | None = None,
        output_validators: list[OutputValidator] | None = None,
        output_functions: list[OutputFunction] | None = None,
        hooks: list[PythonCapability] | None = None,
    ) -> None: ...

class PythonCapability:
    def __init__(
        self,
        id: str,  # noqa: A002
        on_run_start: object,
        event_loop: object | None,
    ) -> None: ...

class EnvironmentProvider:
    @staticmethod
    def python_provider(
        provider: object,
        event_loop: object,
        id: str | None = None,  # noqa: A002
    ) -> EnvironmentProvider: ...
    @staticmethod
    def virtual_provider(
        id: str = "virtual",  # noqa: A002
        files: object | None = None,
        resources: object | None = None,
        shell_outputs: object | None = None,
        tmp_namespace: str | None = None,
    ) -> EnvironmentProvider: ...
    @staticmethod
    def local(
        root: str,
        id: str | None = None,  # noqa: A002
        allowed_paths: list[str] | None = None,
        context_file_tree_roots: list[str] | None = None,
        writable: bool = False,
        allow_shell: bool = False,
        allowed_programs: list[str] | None = None,
        tmp_namespace: str | None = None,
    ) -> EnvironmentProvider: ...
    @staticmethod
    def composite(
        mount_ids: list[str],
        providers: object,
        id: str | None = None,  # noqa: A002
        modes: list[str] | None = None,
        defaults: list[bool] | None = None,
        default_for_shell: list[bool] | None = None,
    ) -> EnvironmentProvider: ...
    @staticmethod
    def envd_local(
        environment: object,
        environment_id: str | None = None,
        id: str | None = None,  # noqa: A002
    ) -> EnvironmentProvider: ...
    @staticmethod
    def envd_http(
        endpoint: str,
        environment_id: str | None = None,
        token: str | None = None,
        id: str | None = None,  # noqa: A002
    ) -> EnvironmentProvider: ...
    @staticmethod
    def envd_stdio(
        program: str,
        args: list[str] | None = None,
        environment_id: str | None = None,
        id: str | None = None,  # noqa: A002
    ) -> EnvironmentProvider: ...
    @property
    def id(self) -> str: ...
    def read_text(self, path: str) -> Awaitable[str]: ...
    def read_bytes(
        self,
        path: str,
        offset: int,
        length: int | None = None,
    ) -> Awaitable[bytes]: ...
    def write_text(self, path: str, content: str) -> Awaitable[None]: ...
    def write_tmp_file(self, filename: str, content: object) -> Awaitable[str]: ...
    def create_dir(self, path: str, parents: bool) -> Awaitable[None]: ...
    def delete_path(self, path: str, recursive: bool) -> Awaitable[None]: ...
    def move_path(self, src: str, dst: str, overwrite: bool) -> Awaitable[None]: ...
    def copy_path(self, src: str, dst: str, overwrite: bool) -> Awaitable[None]: ...
    def list(self, path: str) -> Awaitable[list[str]]: ...
    def list_with_options(
        self,
        path: str,
        max_entries: int = 0,
        ignore_patterns: list[str] | None = None,
    ) -> Awaitable[dict[str, object]]: ...
    def stat(self, path: str) -> Awaitable[dict[str, object]]: ...
    def glob(
        self,
        path: str,
        pattern: str,
        include_hidden: bool = False,
        include_ignored: bool = False,
        max_results: int = 500,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def grep(
        self,
        path: str,
        pattern: str,
        include: str | None = None,
        context_lines: int = 0,
        max_results: int = 100,
        max_matches_per_file: int = 20,
        max_files: int = 50,
        include_hidden: bool = False,
        include_ignored: bool = False,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def render_context(self) -> Awaitable[str | None]: ...
    def inspect_lifecycle(self) -> Awaitable[dict[str, object]]: ...
    def prepare(self) -> Awaitable[dict[str, object]]: ...
    def stop(self) -> Awaitable[dict[str, object]]: ...
    def cleanup_idle(self) -> Awaitable[dict[str, object]]: ...
    def run_shell(
        self,
        command: str,
        timeout_seconds: int | None = None,
        cwd: str | None = None,
        environment: object | None = None,
    ) -> Awaitable[dict[str, object]]: ...
    def start_process(
        self,
        command: str,
        timeout_seconds: int | None = None,
        cwd: str | None = None,
        environment: object | None = None,
    ) -> Awaitable[dict[str, object]]: ...
    def wait_process(
        self,
        process_id: str,
        timeout_seconds: int = 0,
    ) -> Awaitable[dict[str, object]]: ...
    def list_processes(self) -> Awaitable[list[dict[str, object]]]: ...
    def input_process(
        self,
        process_id: str,
        text: str,
        close_stdin: bool = False,
    ) -> Awaitable[dict[str, object]]: ...
    def signal_process(
        self,
        process_id: str,
        signal: int,
    ) -> Awaitable[dict[str, object]]: ...
    def kill_process(self, process_id: str) -> Awaitable[dict[str, object]]: ...
    def export_state(self) -> Awaitable[dict[str, object]]: ...

class MediaUploader:
    def __init__(self, callback: object, event_loop: object) -> None: ...

class Subagent:
    def __init__(
        self,
        name: str,
        agent: object,
        description: str | None = None,
        required_tools: list[str] | None = None,
        optional_tools: list[str] | None = None,
        denied_tools: list[str] | None = None,
        auto_inherit: bool = True,
        inherit_all_when_empty: bool = False,
        allow_nested_delegation: bool = False,
        inherit_hooks: bool = False,
        inherit_capability_bundles: bool = False,
        denied_capabilities: list[str] | None = None,
    ) -> None: ...

class ToolContext:
    @property
    def agent_id(self) -> str | None: ...
    @property
    def run_id(self) -> str: ...
    @property
    def session_id(self) -> str | None: ...
    @property
    def conversation_id(self) -> str: ...
    @property
    def run_step(self) -> int: ...
    @property
    def retry(self) -> int: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def metadata(self) -> dict[str, object]: ...
    @property
    def run_attachments(self) -> dict[str, object]: ...
    @property
    def approval(self) -> dict[str, object] | None: ...
    @property
    def deferred_result(self) -> object | None: ...
    def is_cancelled(self) -> bool: ...
    def cancelled(self) -> Awaitable[bool]: ...
    @property
    def context_handle(self) -> AgentContextHandle | None: ...
    @property
    def workspace_root(self) -> str | None: ...
    @property
    def environment(self) -> EnvironmentProvider | None: ...
    @property
    def raw_context(self) -> dict[str, object] | None: ...
    def export_resources(self) -> Awaitable[object] | None: ...

class AgentContextHandle:
    @property
    def metadata(self) -> dict[str, object]: ...
    def snapshot(self) -> dict[str, object]: ...
    def set_metadata(self, key: str, value: object) -> None: ...

class ToolResult:
    def __init__(
        self,
        content: object,
        metadata: object | None = None,
        app_value: object | None = None,
        model_content: object | None = None,
        user_content: object | None = None,
        private_metadata: object | None = None,
    ) -> None: ...
    @property
    def content(self) -> object: ...
    @property
    def metadata(self) -> dict[str, object]: ...
    @property
    def app_value(self) -> object | None: ...
    @property
    def model_content(self) -> object | None: ...
    @property
    def user_content(self) -> object | None: ...
    @property
    def private_metadata(self) -> dict[str, object]: ...

class PythonTool:
    def __init__(
        self,
        name: str,
        description: str | None,
        parameters_schema: object,
        callback: object,
        event_loop: object,
        return_schema: object | None = None,
        metadata: object | None = None,
        strict: bool | None = None,
        sequential: bool | None = None,
        timeout_ms: int | None = None,
        max_retries: int | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    def definition_json(self) -> dict[str, object]: ...

class ToolsetContext:
    @property
    def agent_id(self) -> str: ...
    @property
    def run_id(self) -> str | None: ...
    @property
    def session_id(self) -> str | None: ...
    @property
    def conversation_id(self) -> str: ...
    @property
    def run_step(self) -> int: ...
    @property
    def metadata(self) -> dict[str, object]: ...
    @property
    def run_attachments(self) -> dict[str, object]: ...
    @property
    def workspace_root(self) -> str | None: ...
    @property
    def environment(self) -> EnvironmentProvider | None: ...
    @property
    def resources(self) -> object: ...
    @property
    def raw_context(self) -> dict[str, object]: ...

class ToolsetLifecyclePolicy:
    def __init__(
        self,
        initialization_timeout_ms: int | None = None,
        read_timeout_ms: int | None = None,
        exit_timeout_ms: int | None = None,
        enter_before_prepare: bool = True,
        exit_after_run: bool = True,
        fail_on_unavailable: bool = False,
    ) -> None: ...
    @property
    def initialization_timeout_ms(self) -> int | None: ...
    @property
    def read_timeout_ms(self) -> int | None: ...
    @property
    def exit_timeout_ms(self) -> int | None: ...
    @property
    def enter_before_prepare(self) -> bool: ...
    @property
    def exit_after_run(self) -> bool: ...
    @property
    def fail_on_unavailable(self) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...

class Toolset:
    def __init__(
        self,
        name: str,
        tools: list[PythonTool] | None = None,
        instructions: list[str] | None = None,
        id: str | None = None,  # noqa: A002
        max_retries: int | None = None,
        timeout_ms: int | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> str | None: ...
    def tool_definitions(self) -> list[dict[str, object]]: ...
    def instructions(self) -> list[dict[str, object]]: ...

def tool_search_toolset(
    toolsets: list[Toolset],
    max_results: int | None = None,
) -> Toolset: ...
def tool_proxy_toolset(
    toolsets: list[Toolset],
    prefix: str | None = None,
    max_results: int | None = None,
    namespace_descriptions: dict[str, str] | None = None,
) -> Toolset: ...
def combined_toolset(
    name: str,
    toolsets: list[Toolset],
    id: str | None = None,  # noqa: A002
    max_retries: int | None = None,
    timeout_ms: int | None = None,
) -> Toolset: ...
def mcp_toolset(config: object) -> Toolset: ...
def dynamic_toolset(
    name: str,
    prepare_callback: object,
    refresh_callback: object,
    enter_callback: object,
    exit_callback: object,
    event_loop: object,
    id: str | None = None,  # noqa: A002
    max_retries: int | None = None,
    timeout_ms: int | None = None,
    lifecycle_policy: ToolsetLifecyclePolicy | None = None,
) -> Toolset: ...
def prepared_toolset(
    toolset: Toolset,
    callback: object,
    event_loop: object,
) -> Toolset: ...
def prefixed_toolset(toolset: Toolset, prefix: str) -> Toolset: ...
def filtered_toolset(
    toolset: Toolset,
    include: list[str] | None = None,
    exclude: list[str] | None = None,
) -> Toolset: ...
def renamed_toolset(toolset: Toolset, mappings: dict[str, str]) -> Toolset: ...
def metadata_toolset(toolset: Toolset, metadata: object) -> Toolset: ...
def approval_required_toolset(
    toolset: Toolset,
    names: list[str],
    reason: str | None = None,
) -> Toolset: ...
def deferred_toolset(
    toolset: Toolset,
    names: list[str],
    reason: str | None = None,
) -> Toolset: ...
def core_toolsets() -> list[Toolset]: ...
def filesystem_toolset() -> Toolset: ...
def shell_toolset() -> Toolset: ...
def environment_toolsets() -> list[Toolset]: ...
def host_io_toolset() -> Toolset: ...
def task_toolset() -> Toolset: ...
def context_toolset() -> Toolset: ...

class SkillPackage:
    def __init__(
        self,
        name: str,
        description: str,
        path: str,
        body: str | None = None,
        metadata: object | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def body(self) -> str | None: ...
    @property
    def metadata(self) -> dict[str, object]: ...
    def summary_line(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

class SkillRegistry:
    def __init__(self, packages: list[SkillPackage] | None = None) -> None: ...
    @staticmethod
    def parse(path: str, content: str) -> SkillPackage: ...
    @staticmethod
    def scan(
        environment: EnvironmentProvider,
        scopes: object | None = None,
    ) -> Awaitable[SkillRegistry]: ...
    @staticmethod
    def scan_with_report(
        environment: EnvironmentProvider,
        scopes: object | None = None,
    ) -> Awaitable[dict[str, object]]: ...
    @staticmethod
    def activate(
        environment: EnvironmentProvider,
        path: str,
    ) -> Awaitable[SkillPackage]: ...
    def insert(self, package: SkillPackage) -> None: ...
    def get(self, name: str) -> SkillPackage | None: ...
    @property
    def packages(self) -> list[SkillPackage]: ...
    @property
    def is_empty(self) -> bool: ...
    def toolset(self) -> Toolset: ...
    def to_dict(self) -> dict[str, object]: ...

class SqliteReplayEventLog:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def open(path: str) -> SqliteReplayEventLog: ...
    @staticmethod
    def in_memory() -> SqliteReplayEventLog: ...
    def append(self, scope: str, event: object) -> Awaitable[None]: ...
    def replay_after(
        self,
        scope: str,
        cursor: object | None = None,
        limit: int | None = None,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def compact_snapshot(self, scope: str) -> Awaitable[dict[str, object]]: ...
    def save_snapshot(self, scope: str, snapshot: object) -> Awaitable[None]: ...

class PythonSessionStore:
    def __init__(self, store: object, event_loop: object) -> None: ...
    def save_session(self, record: object) -> Awaitable[None]: ...
    def load_session(self, session_id: str) -> Awaitable[dict[str, object]]: ...
    def list_sessions(
        self,
        filter: object | None = None,  # noqa: A002
    ) -> Awaitable[list[dict[str, object]]]: ...
    def update_session_status(self, session_id: str, status: str) -> Awaitable[None]: ...
    def save_context_state(self, session_id: str, state: object) -> Awaitable[None]: ...
    def save_environment_state(
        self,
        session_id: str,
        environment_state: object,
    ) -> Awaitable[None]: ...
    def append_run(self, record: object) -> Awaitable[None]: ...
    def load_run(self, session_id: str, run_id: str) -> Awaitable[dict[str, object]]: ...
    def list_runs(self, session_id: str) -> Awaitable[list[dict[str, object]]]: ...
    def update_run_status(
        self,
        session_id: str,
        run_id: str,
        status: str,
        output_preview: str | None = None,
    ) -> Awaitable[None]: ...
    def append_checkpoint(self, session_id: str, checkpoint: object) -> Awaitable[None]: ...
    def load_checkpoints(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def append_stream_records(
        self,
        session_id: str,
        run_id: str,
        records: object,
    ) -> Awaitable[None]: ...
    def replay_stream_records(
        self,
        session_id: str,
        run_id: str,
        after_sequence: int | None = None,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def save_stream_cursor(
        self,
        session_id: str,
        run_id: str,
        cursor: object,
    ) -> Awaitable[None]: ...
    def append_approval(self, record: object) -> Awaitable[None]: ...
    def load_approvals(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def append_deferred_tool(self, record: object) -> Awaitable[None]: ...
    def load_deferred_tools(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def resume_snapshot(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[dict[str, object]]: ...
    def compact_run_trace(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[dict[str, object]]: ...
    def compact_session_trace(self, session_id: str) -> Awaitable[dict[str, object]]: ...

class SqliteSessionStore:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def open(path: str) -> SqliteSessionStore: ...
    @staticmethod
    def in_memory() -> SqliteSessionStore: ...
    @staticmethod
    def migrate(path: str) -> list[str]: ...
    @staticmethod
    def migration_status(path: str) -> dict[str, object]: ...
    def save_session(self, record: object) -> Awaitable[None]: ...
    def load_session(self, session_id: str) -> Awaitable[dict[str, object]]: ...
    def list_sessions(
        self,
        filter: object | None = None,  # noqa: A002
    ) -> Awaitable[list[dict[str, object]]]: ...
    def update_session_status(self, session_id: str, status: str) -> Awaitable[None]: ...
    def save_context_state(self, session_id: str, state: object) -> Awaitable[None]: ...
    def save_environment_state(
        self,
        session_id: str,
        environment_state: object,
    ) -> Awaitable[None]: ...
    def append_run(self, record: object) -> Awaitable[None]: ...
    def load_run(self, session_id: str, run_id: str) -> Awaitable[dict[str, object]]: ...
    def list_runs(self, session_id: str) -> Awaitable[list[dict[str, object]]]: ...
    def update_run_status(
        self,
        session_id: str,
        run_id: str,
        status: str,
        output_preview: str | None = None,
    ) -> Awaitable[None]: ...
    def append_checkpoint(self, session_id: str, checkpoint: object) -> Awaitable[None]: ...
    def load_checkpoints(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def append_stream_records(
        self,
        session_id: str,
        run_id: str,
        records: object,
    ) -> Awaitable[None]: ...
    def replay_stream_records(
        self,
        session_id: str,
        run_id: str,
        after_sequence: int | None = None,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def save_stream_cursor(
        self,
        session_id: str,
        run_id: str,
        cursor: object,
    ) -> Awaitable[None]: ...
    def append_approval(self, record: object) -> Awaitable[None]: ...
    def load_approvals(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def append_deferred_tool(self, record: object) -> Awaitable[None]: ...
    def load_deferred_tools(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def resume_snapshot(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[dict[str, object]]: ...
    def compact_run_trace(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[dict[str, object]]: ...
    def compact_session_trace(self, session_id: str) -> Awaitable[dict[str, object]]: ...

class SqliteStreamArchive:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def open(path: str) -> SqliteStreamArchive: ...
    @staticmethod
    def in_memory() -> SqliteStreamArchive: ...
    def append_raw_records(
        self,
        session_id: str,
        run_id: str,
        records: object,
    ) -> Awaitable[None]: ...
    def replay_raw_after(
        self,
        session_id: str,
        run_id: str,
        cursor: object | None = None,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def append_display_messages(
        self,
        scope: str,
        messages: object,
    ) -> Awaitable[None]: ...
    def replay_display_after(
        self,
        scope: str,
        cursor: object | None = None,
    ) -> Awaitable[list[dict[str, object]]]: ...
    def append_snapshot(self, scope: str, snapshot: object) -> Awaitable[None]: ...
    def latest_snapshot(self, scope: str) -> Awaitable[dict[str, object] | None]: ...
    def cursor_range(self, scope: str) -> Awaitable[dict[str, object] | None]: ...

class RunResult:
    @property
    def output(self) -> str: ...
    @property
    def structured_output(self) -> object | None: ...
    @property
    def messages(self) -> list[object]: ...
    @property
    def raw_state(self) -> dict[str, object]: ...
    @property
    def status(self) -> str: ...
    @property
    def is_waiting(self) -> bool: ...
    @property
    def needs_approval(self) -> bool: ...
    @property
    def pending_approvals(self) -> list[dict[str, object]]: ...
    @property
    def pending_deferred_tools(self) -> list[dict[str, object]]: ...
    @property
    def pending_deferred(self) -> list[dict[str, object]]: ...

class StreamEvent:
    @property
    def kind(self) -> str: ...
    @property
    def raw(self) -> Any: ...

def display_to_agui(message: object) -> dict[str, object]: ...
def display_to_agui_jsonl(messages: object) -> str: ...

class StreamRunResult:
    @property
    def result(self) -> RunResult: ...
    @property
    def events(self) -> list[StreamEvent]: ...

class AgentStream:
    def recv(self) -> Awaitable[StreamEvent | None]: ...
    def close_receiver(self) -> None: ...
    def detach(self) -> None: ...
    def interrupt(self, reason: str | None = None) -> None: ...
    def steer(self, text: str, id: str | None = None) -> Awaitable[dict[str, object]]: ...  # noqa: A002
    def send_message(self, message: object) -> Awaitable[dict[str, object]]: ...
    def join(self) -> Awaitable[StreamRunResult]: ...
    def result(self) -> Awaitable[RunResult]: ...
    def resume_after_hitl(
        self,
        approvals: object | None = None,
        deferred_results: object | None = None,
    ) -> Awaitable[RunResult]: ...
    def resume_after_hitl_stream(
        self,
        approvals: object | None = None,
        deferred_results: object | None = None,
    ) -> Awaitable[AgentStream]: ...
    def resume_after_hitl_for_state(
        self,
        state: object,
        approvals: object | None = None,
        deferred_results: object | None = None,
    ) -> Awaitable[RunResult]: ...
    def recoverable_state(self) -> Awaitable[dict[str, object]]: ...
    def status(self) -> dict[str, object]: ...

class AgentSession:
    def run(self, prompt: str) -> Awaitable[RunResult]: ...
    def stream(
        self,
        prompt: str,
        instructions: list[str] | None = None,
        tools: list[PythonTool] | None = None,
        replace_tools: bool = False,
        model_settings: object | None = None,
        request_params: object | None = None,
        output_schema: object | None = None,
        output_policy: object | None = None,
        trace_metadata: object | None = None,
        toolsets: list[Toolset] | None = None,
        environment: EnvironmentProvider | None = None,
        context_metadata: object | None = None,
        tool_config: object | None = None,
        security: object | None = None,
    ) -> AgentStream: ...
    def export_state(self, mode: str | None = None) -> dict[str, object]: ...
    @property
    def metadata(self) -> dict[str, object]: ...
    def set_metadata(self, key: str, value: object) -> None: ...
    def set_environment(self, environment: EnvironmentProvider) -> None: ...
    def export_environment_state(self) -> Awaitable[dict[str, object] | None]: ...
    def steer(self, text: str, id: str | None = None) -> Awaitable[dict[str, object]]: ...  # noqa: A002
    def interrupt(self, reason: str | None = None) -> None: ...
    def message_send(self, message: object) -> dict[str, object]: ...
    def message_peek(self, agent_id: str | None = None) -> list[dict[str, object]]: ...
    def message_consume(self, agent_id: str | None = None) -> list[dict[str, object]]: ...
    def message_subscribe(self, agent_id: str | None = None) -> None: ...
    def message_unsubscribe(self, agent_id: str | None = None) -> None: ...
    def resume_after_hitl(
        self,
        approvals: object | None = None,
        deferred_results: object | None = None,
    ) -> Awaitable[RunResult]: ...
    def resume_after_hitl_stream(
        self,
        approvals: object | None = None,
        deferred_results: object | None = None,
    ) -> Awaitable[AgentStream]: ...
    def resume_after_hitl_for_state(
        self,
        state: object,
        approvals: object | None = None,
        deferred_results: object | None = None,
    ) -> Awaitable[RunResult]: ...

class AgentRuntime:
    def __init__(
        self,
        model: object,
        tools: list[PythonTool] | None = None,
        instructions: list[str] | None = None,
        name: str | None = None,
        model_settings: object | None = None,
        request_params: object | None = None,
        output_schema: object | None = None,
        output_policy: object | None = None,
        subagents: list[Subagent] | None = None,
        subagent_delegation_mode: str | None = None,
        capability_bundles: list[CapabilityBundle] | None = None,
        toolsets: list[Toolset] | None = None,
        approval_required_tools: list[str] | None = None,
        runtime_config: object | None = None,
        skills: SkillRegistry | None = None,
        environment: EnvironmentProvider | None = None,
        media_uploader: MediaUploader | None = None,
        session_store: object | None = None,
        durable_session_id: str | None = None,
        stream_archive: object | None = None,
        replay_event_log: object | None = None,
        state: object | None = None,
        tool_config: object | None = None,
        security: object | None = None,
    ) -> None: ...
    @property
    def durable_session_id(self) -> str | None: ...
    def run(self, prompt: str) -> Awaitable[RunResult]: ...
    def run_stream(self, prompt: str) -> Awaitable[StreamRunResult]: ...
    def stream(self, prompt: str) -> AgentStream: ...
    def export_state(self) -> dict[str, object]: ...
    def export_full_state(self) -> dict[str, object]: ...
    def export_environment_state(self) -> Awaitable[dict[str, object] | None]: ...
    def set_environment(self, environment: EnvironmentProvider) -> None: ...
    def resume_snapshot(
        self,
        session_id: str,
        run_id: str,
    ) -> Awaitable[dict[str, object]]: ...
    def resume_after_hitl_by_id(
        self,
        session_id: str,
        run_id: str,
        approvals: object | None = None,
        deferred_results: object | None = None,
    ) -> Awaitable[RunResult]: ...

class Agent:
    def __init__(
        self,
        model: object,
        tools: list[PythonTool] | None = None,
        instructions: list[str] | None = None,
        name: str | None = None,
        model_settings: object | None = None,
        request_params: object | None = None,
        output_schema: object | None = None,
        output_policy: object | None = None,
        subagents: list[Subagent] | None = None,
        subagent_delegation_mode: str | None = None,
        capability_bundles: list[CapabilityBundle] | None = None,
        toolsets: list[Toolset] | None = None,
        approval_required_tools: list[str] | None = None,
        runtime_config: object | None = None,
        skills: SkillRegistry | None = None,
        environment: EnvironmentProvider | None = None,
        media_uploader: MediaUploader | None = None,
        tool_config: object | None = None,
        security: object | None = None,
    ) -> None: ...
    def run(self, prompt: str) -> Awaitable[RunResult]: ...
    def stream(
        self,
        prompt: str,
        instructions: list[str] | None = None,
        tools: list[PythonTool] | None = None,
        replace_tools: bool = False,
        model_settings: object | None = None,
        request_params: object | None = None,
        output_schema: object | None = None,
        output_policy: object | None = None,
        trace_metadata: object | None = None,
        toolsets: list[Toolset] | None = None,
        environment: EnvironmentProvider | None = None,
        context_metadata: object | None = None,
        tool_config: object | None = None,
        security: object | None = None,
    ) -> AgentStream: ...
    def new_session(self, environment: EnvironmentProvider | None = None) -> AgentSession: ...
    def session_from_state(
        self,
        state: object,
        environment: EnvironmentProvider | None = None,
    ) -> AgentSession: ...
